/**
 * This file was automatically generated by generate-types.sh.
 *
 * DO NOT MODIFY IT BY HAND.
 *
 * Instead:
 * - modify the validation/*.schema.json files;
 * - then, run generate-types.sh to regenerate this file.
 */

/**
 * Note: CE SCHEMA EST INCOMPLET POUR L'INSTANT. Cf https://github.com/signaux-faibles/opensignauxfaibles/pull/143
 */
export interface EntréeBdf {
  siren: string
}
/**
 * Note: CE SCHEMA EST INCOMPLET POUR L'INSTANT. Cf https://github.com/signaux-faibles/opensignauxfaibles/pull/143
 */
export interface EntréeDelai {
  date_creation: Date
  date_echeance: Date
  /**
   * Doit valoir 1 ou plus:
   */
  duree_delai: number
  /**
   * Doit valoir plus que 0 euros:
   */
  montant_echeancier: number
}
