// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-01-22 17:16:26.7147923 +0100 CET m=+0.133632935

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "Cette API centralise toutes les fonctionnalités du module de traitement de données OpenSignauxFaibles\nPour plus de renseignements: https://beta.gouv.fr/startups/signaux-faibles.html",
        "title": "API openSignauxFaibles",
        "contact": {},
        "license": {
            "name": "Licence MIT",
            "url": "https://raw.githubusercontent.com/entrepreneur-interet-general/opensignauxfaibles/master/LICENSE"
        },
        "version": "1.1"
    },
    "host": "{{.Host}}",
    "basePath": "/",
    "paths": {
        "/api/admin/batch": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Produit une extraction des objets batch de la collection Admin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Administration"
                ],
                "summary": "Liste des batches",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/admin/batch/next": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Exécute l'import, le compactage et la réduction du dernier batch",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Administration"
                ],
                "summary": "Traitement du dernier batch",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/admin/epoch": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Ce numéro s'incrémente à chaque action",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Administration"
                ],
                "summary": "Numéro du statut du serveur",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/admin/features": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Correspond aux mapReduces qui produisent les variables dans la collection Features",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Administration"
                ],
                "summary": "Identifiants des traitements de réduction",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/admin/files": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Tous ces fichiers sont contenu dans APP_DATA (voir config.toml)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Administration"
                ],
                "summary": "Liste les fichiers disponibles dans le dépot",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Réalise l'upload d'un fichier dans un batch/type. Une fois l'upload effectué, le fichier est automatiquement attaché au batch.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Administration"
                ],
                "summary": "Upload d'un fichier",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/admin/getLogs": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Liste les 100 derniers évènements du journal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Administration"
                ],
                "summary": "Journal d'évènements",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/admin/status": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Permet de connaître l'opération en cours",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Administration"
                ],
                "summary": "Disponibilité de la base de données",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/admin/types": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Correspond aux types disponibles dans les traitements d'importation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Administration"
                ],
                "summary": "Liste des types",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/data/batch/purge": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Exécute l'import, le compactage et la réduction du dernier batch",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Administration"
                ],
                "summary": "Traitement du dernier batch",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/data/compact": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Alimente la collection Features",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Traitements"
                ],
                "summary": "Lance un traitement de compactage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Identifiant du traitement",
                        "name": "algo",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Identifier du batch",
                        "name": "batch",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/data/import/{batch}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Effectue l'import de tous les fichiers du batch donné en paramètre",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Traitements"
                ],
                "summary": "Import de fichiers pour un batch",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Clé du batch",
                        "name": "batch",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/data/purge": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Suppression de tous les objets de données brutes contenus dans la collection RawData (irréversible)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Traitements"
                ],
                "summary": "Purge la collection RawData",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/data/reduce/{algo}/{batch}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Alimente la collection Features",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Traitements"
                ],
                "summary": "Lance un traitement de réduction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Identifiant du traitement",
                        "name": "algo",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Identifier du batch",
                        "name": "batch",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/data/search": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Effectue une recherche texte sur la collection Public et retourne les 15 premiers objets correspondants",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Traitements"
                ],
                "summary": "Rechercher une entreprise",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chaine à chercher",
                        "name": "guessRaisonSociale",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/reduce/{algo}/{batch}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Alimente la collection Features",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Traitements"
                ],
                "summary": "Remplace un batch",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Identifiant du traitement",
                        "name": "algo",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Identifier du batch",
                        "name": "batch",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/refreshToken": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Fournit un jeton avec nouvelle date de validité en échange d'un jeton encore valide",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Session"
                ],
                "summary": "Obtenir un jeton d'identification",
                "responses": {
                    "200": {
                        "description": "{\u003cbr/\u003e'code': 200,\u003cbr/\u003e   'expire': '2019-01-21T12:16:50+01:00',\u003cbr/\u003e'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9…'\u003cbr/\u003e}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "{\u003cbr/\u003e'code': 401,\u003cbr/\u003e'message': 'cookie token is empty'\u003cbr/\u003e}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Nécessite 3 informations: email, mot de passe et jeton de navigateur\nLe jeton de navigateur n'a pas de limite de validité et peut être conservé",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Session"
                ],
                "summary": "Rafraichir le jeton d'identification",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Adresse Email",
                        "name": "email",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Mot de Passe",
                        "name": "password",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Token navigateur",
                        "name": "browserToken",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\u003cbr/\u003e'code': 200,\u003cbr/\u003e'expire':'2019-01-21T11:16:15+01:00',\u003cbr/\u003e'token':'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9…'\u003cbr/\u003e}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "{\u003cbr/\u003e'code': 401,\u003cbr/\u003e'message': 'incorrect Username or Password'\u003cbr/\u003e}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login/check": {
            "post": {
                "description": "Fournit en retour un jeton de navigateur",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Session"
                ],
                "summary": "Vérification du code temporaire renvoyé à l'utilisateur",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Adresse EMail",
                        "name": "email",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Mot de passe",
                        "name": "password",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Code de vérification",
                        "name": "checkCode",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login/recovery/get": {
            "post": {
                "description": "Dans le cas d'un oubli du mot de passe, on peut fixer un nouveau mot de passe à partir d'un navigateur identifié\nIl faut dans ce cas pouvoir recevoir un code de vérification par mail\nVoir /login/recovery/get",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Session"
                ],
                "summary": "Récupération du mot de passe",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login/recovery/setPassword": {
            "post": {
                "description": "Dans le cas d'un oubli du mot de passe, on peut fixer un nouveau mot de passe à partir d'un navigateur identifié\nIl faut dans ce cas pouvoir recevoir un code de vérification par mail\nVoir /login/recovery/get",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Session"
                ],
                "summary": "Récupération du mot de passe",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
