// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-02-12 13:01:11.08336386 +0100 CET m=+0.096161419

package docs

import (
	"bytes"
	"io/ioutil"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var jsonDoc, _ = ioutil.ReadFile("docs/swagger/swagger.json")
var doc = string(jsonDoc)

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
