/* Generated by bundle-schemas.go - DO NOT EDIT */

package engine

var validationSchemas = map[string]string{
"apconso.schema.json": `{
  "title": "EntréeApConso",
  "description": "Champs importés par le parseur lib/apconso/main.go de sfdata.",
  "bsonType": "object",
  "required": ["id_conso", "periode", "heure_consomme", "montant", "effectif"],
  "properties": {
    "id_conso": {
      "bsonType": "string"
    },
    "heure_consomme": {
      "bsonType": "number"
    },
    "montant": {
      "bsonType": "number"
    },
    "effectif": {
      "bsonType": "number"
    },
    "periode": {
      "bsonType": "date"
    }
  },
  "additionalProperties": false
}
`,
"apdemande.schema.json": `{
  "title": "EntréeApDemande",
  "description": "Champs importés par le parseur lib/apdemande/main.go de sfdata.",
  "bsonType": "object",
  "required": [
    "id_demande",
    "periode",
    "hta",
    "motif_recours_se",
    "effectif_entreprise",
    "effectif",
    "date_statut",
    "mta",
    "effectif_autorise",
    "heure_consommee",
    "montant_consommee",
    "effectif_consomme"
  ],
  "properties": {
    "id_demande": {
      "bsonType": "string"
    },
    "periode": {
      "bsonType": "object",
      "required": ["start", "end"],
      "properties": {
        "start": { "bsonType": "date" },
        "end": { "bsonType": "date" }
      },
      "additionalProperties": false
    },
    "hta": {
      "description": "Nombre total d'heures autorisées",
      "bsonType": "number"
    },
    "motif_recours_se": {
      "description": "Cause d'activité partielle",
      "bsonType": "number"
    },
    "effectif_entreprise": {
      "bsonType": "number"
    },
    "effectif": {
      "bsonType": "number"
    },
    "date_statut": {
      "bsonType": "date"
    },
    "mta": {
      "bsonType": "number"
    },
    "effectif_autorise": {
      "bsonType": "number"
    },
    "heure_consommee": {
      "bsonType": "number"
    },
    "montant_consommee": {
      "bsonType": "number"
    },
    "effectif_consomme": {
      "bsonType": "number"
    }
  },
  "additionalProperties": false
}
`,
"bdf.schema.json": `{
  "title": "EntréeBdf",
  "description": "Note: CE SCHEMA EST INCOMPLET POUR L'INSTANT. Cf https://github.com/signaux-faibles/opensignauxfaibles/pull/143",
  "bsonType": "object",
  "required": ["siren"],
  "properties": {
    "siren": {
      "bsonType": "string",
      "pattern": "^[0-9]{9}$"
    }
  },
  "additionalProperties": false
}
`,
"ccsf.schema.json": `{
  "title": "EntréeCcsf",
  "description": "Champs importés par le parseur lib/urssaf/ccsf.go de sfdata.",
  "bsonType": "object",
  "required": ["date_traitement", "stade", "action"],
  "properties": {
    "date_traitement": {
      "bsonType": "date",
      "description": "Date de début de la procédure CCSF"
    },
    "stade": {
      "bsonType": "string",
      "description": "TODO: choisir un type plus précis"
    },
    "action": {
      "bsonType": "string",
      "description": "TODO: choisir un type plus précis"
    }
  },
  "additionalProperties": false
}
`,
"compte.schema.json": `{
  "title": "EntréeCompte",
  "description": "Champs importés par le parseur lib/urssaf/compte.go de sfdata.",
  "bsonType": "object",
  "required": ["periode", "siret", "numero_compte"],
  "properties": {
    "periode": {
      "bsonType": "date",
      "description": "Date à laquelle cet établissement est associé à ce numéro de compte URSSAF."
    },
    "siret": {
      "bsonType": "string",
      "description": "Numéro SIRET de l'établissement. Les numéros avec des Lettres sont des sirets provisoires."
    },
    "numero_compte": {
      "bsonType": "string",
      "description": "Compte administratif URSSAF."
    }
  },
  "additionalProperties": false
}
`,
"cotisation.schema.json": `{
  "title": "EntréeCotisation",
  "description": "Champs importés par le parseur lib/urssaf/cotisation.go de sfdata.",
  "bsonType": "object",
  "required": ["numero_compte", "periode", "encaisse", "du"],
  "properties": {
    "numero_compte": {
      "description": "Compte administratif URSSAF.",
      "bsonType": "string"
    },
    "periode": {
      "description": "Période sur laquelle le montants s'appliquent.",
      "bsonType": "object",
      "required": ["start", "end"],
      "properties": {
        "start": { "bsonType": "date" },
        "end": { "bsonType": "date" }
      },
      "additionalProperties": false
    },
    "encaisse": {
      "description": "Cotisation encaissée directement, en euros.",
      "bsonType": "number"
    },
    "du": {
      "description": "Cotisation due, en euros. À utiliser pour calculer le montant moyen mensuel du: Somme cotisations dues / nb périodes.",
      "bsonType": "number"
    }
  },
  "additionalProperties": false
}
`,
"debit.schema.json": `{
  "title": "EntréeDebit",
  "description": "Champs importés par le parseur lib/sirene_ul/main.go de sfdata. Représente un reste à payer (dette) sur cotisation sociale ou autre.",
  "bsonType": "object",
  "required": [
    "numero_compte",
    "numero_ecart_negatif",
    "date_traitement",
    "part_ouvriere",
    "part_patronale",
    "numero_historique",
    "etat_compte",
    "code_procedure_collective",
    "periode",
    "code_operation_ecart_negatif",
    "code_motif_ecart_negatif",
    "recours_en_cours"
  ],
  "properties": {
    "numero_compte": {
      "description": "Identifiant URSSAF d'établissement (équivalent du SIRET).",
      "bsonType": "string"
    },
    "periode": {
      "description": "Période sur laquelle le montants s'appliquent.",
      "bsonType": "object",
      "required": ["start", "end"],
      "properties": {
        "start": { "bsonType": "date" },
        "end": { "bsonType": "date" }
      },
      "additionalItems": false
    },
    "numero_ecart_negatif": {
      "description": "L'écart négatif (ecn) correspond à une période en débit. Pour une même période, plusieurs débits peuvent être créés. On leur attribue un numéro d'ordre. Par exemple, 101, 201, 301 etc.; ou 101, 102, 201 etc. correspondent respectivement au 1er, 2ème et 3ème ecn de la période considérée.",
      "bsonType": "string"
    },
    "numero_historique": {
      "description": "Ordre des opérations pour un écart négatif donné.",
      "bsonType": "number"
    },
    "date_traitement": {
      "description": "Date de constatation du débit (exemple: remboursement, majoration ou autre modification du montant)",
      "bsonType": "date"
    },
    "debit_suivant": {
      "description": "Hash d'un autre débit // TODO: non fourni par le parseur, ce champ devrait être défini dans un type de sortie.",
      "bsonType": "string"
    },
    "part_ouvriere": {
      "description": "Montant des débits sur la part ouvrières, exprimées en euros (€). Sont exclues les pénalités et les majorations de retard.",
      "bsonType": "number"
    },
    "part_patronale": {
      "description": "Montant des débits sur la part patronale, exprimées en euros (€). Sont exclues les pénalités et les majorations de retard.",
      "bsonType": "number"
    },
    "etat_compte": {
      "description": "Code état du compte: 1 (Actif), 2 (Suspendu) ou 3 (Radié).",
      "bsonType": "number"
    },
    "code_procedure_collective": {
      "description": "Code qui indique si le compte fait l'objet d'une procédure collective: 1 (en cours), 2 (plan de redressement en cours), 9 (procedure collective sans dette à l'Urssaf) ou valeur nulle en cas d'absence de procédure collective.",
      "bsonType": "string"
    },
    "code_operation_ecart_negatif": {
      "description": "Code opération historique de l'écart négatif: \n 1 Mise en recouvrement \n 2 Paiement \n 3 Admission en non valeur \n 4 Remise de majoration de retard \n 5 Abandon de solde debiteur \n 11 Annulation de mise en recouvrement \n 12 Annulation paiement \n 13 Annulation a-n-v \n 14 Annulation de remise de majoration retard \n 15 Annulation abandon solde debiteur",
      "bsonType": "string"
    },
    "code_motif_ecart_negatif": {
      "description": "Code motif de l'écart négatif: \n 0 Cde motif inconnu \n 1 Retard dans le versement \n 2 Absence ou insuffisance de versement \n 3 Taxation provisionelle. Déclarations non fournies \n 4 Majorations de retard complémentaires Article R243-18 du code de la sécurité sociale \n 5 Contrôle,chefs de redressement notifiés le JJ/MM/AA Article R243-59 de la Securité Sociale \n 6 Fourniture tardive des déclarations \n 7 Bases déclarées supérieures à Taxation provisionnelle \n 8 Retard dans le versement et fourniture tardive des déclarations \n 9 Absence ou insuffisance de versement et fourniture tardive des déclarations \n 10 Rappel sur contrôle et fourniture tardive des déclarations \n 11 Régularisation d'une taxation provisionnelle \n 12 Régularisation annuelle \n 13 Rejet du titre de paiement par la banque . \n 14 Modification d'affectation d'un crédit \n 15 Annulation d'un crédit \n 16 Régularisation suite à modification du Taux Accident du Travail \n 17 Régularisation suite à assujettissement au transport (origine débit sur PJ=4) \n 18 Majorations pour non respect de paiement par moyen dématérialisé Article L243-14 \n 19 Rapprochement TR/BRC sous réserve de vérification ultérieure \n 20 Cotisations complémentaires suite modification des revenus déclarés \n 21 Cotisations complémentaires suite à non fourniture du contrat d'exonération \n 22 Contrôle. Chefs de redressement notifiés le JJ/MM/AA. Article L324.9 du code du travail \n 23 Cotisations complémentaires suite conditions d'exonération non remplies \n 24 Absence de versement \n 25 Insuffisance de versement \n 26 Absence de versement et fourniture tardive des déclarations \n 27 Insuffisance de versement et fourniture tardive des déclarations",
      "bsonType": "string"
    },
    "recours_en_cours": {
      "description": "Recours en cours.",
      "bsonType": "bool"
    }
  },
  "additionalProperties": false
}
`,
"delai.schema.json": `{
  "title": "EntréeDelai",
  "description": "Champs importés par le parseur lib/urssaf/delai.go de sfdata.",
  "bsonType": "object",
  "required": [
    "numero_compte",
    "numero_contentieux",
    "date_creation",
    "date_echeance",
    "duree_delai",
    "denomination",
    "indic_6m",
    "annee_creation",
    "montant_echeancier",
    "stade",
    "action"
  ],
  "properties": {
    "numero_compte": {
      "bsonType": "string",
      "description": "Compte administratif URSSAF."
    },
    "numero_contentieux": {
      "bsonType": "string",
      "description": "Le numéro de structure est l'identifiant d'un dossier contentieux."
    },
    "date_creation": {
      "bsonType": "date",
      "description": "Date de création du délai."
    },
    "date_echeance": {
      "bsonType": "date",
      "description": "Date d'échéance du délai."
    },
    "duree_delai": {
      "bsonType": "number",
      "description": "Durée du délai en jours: nombre de jours entre date_creation et date_echeance.",
      "minimum": 1
    },
    "denomination": {
      "bsonType": "string",
      "description": "Raison sociale de l'établissement."
    },
    "indic_6m": {
      "bsonType": "string",
      "description": "Délai inférieur ou supérieur à 6 mois ? Modalités INF et SUP."
    },
    "annee_creation": {
      "bsonType": "number",
      "description": "Année de création du délai."
    },
    "montant_echeancier": {
      "bsonType": "number",
      "description": "Montant global de l'échéancier, en euros.",
      "minimum": 0.01
    },
    "stade": {
      "bsonType": "string",
      "description": "Code externe du stade."
    },
    "action": {
      "bsonType": "string",
      "description": "Code externe de l'action."
    }
  },
  "additionalProperties": false
}
`,
"detect_invalid_entries.pipeline.json": `[
  { "$project": { "_id": 1, "batches": { "$objectToArray": "$value.batch" } } },
  { "$unwind": { "path": "$batches", "preserveNullAndEmptyArrays": false } },
  {
    "$project": {
      "_id": 1,
      "batchKey": "$batches.k",
      "dataPerHash": { "$objectToArray": "$batches.v" }
    }
  },
  {
    "$unwind": { "path": "$dataPerHash", "preserveNullAndEmptyArrays": false }
  },
  {
    "$project": {
      "_id": 1,
      "batchKey": 1,
      "dataType": "$dataPerHash.k",
      "dataPerHash": "$dataPerHash.v"
    }
  },
  { "$match": { "dataPerHash": { "$not": { "$type": 3 } } } }
]
`,
"effectif.schema.json": `{
  "title": "EntréeEffectif",
  "description": "Champs importés par le parseur lib/urssaf/effectif.go de sfdata.",
  "bsonType": "object",
  "required": ["numero_compte", "periode", "effectif"],
  "properties": {
    "numero_compte": {
      "description": "Compte administratif URSSAF.",
      "bsonType": "string"
    },
    "periode": {
      "bsonType": "date"
    },
    "effectif": {
      "description": "Nombre de personnes employées par l'établissement.",
      "bsonType": "number"
    }
  },
  "additionalProperties": false
}
`,
"effectif_ent.schema.json": `{
  "title": "EntréeEffectifEnt",
  "description": "Champs importés par le parseur lib/urssaf/effectif_ent.go de sfdata.",
  "bsonType": "object",
  "required": ["periode", "effectif"],
  "properties": {
    "periode": {
      "bsonType": "date"
    },
    "effectif": {
      "description": "Nombre de personnes employées par l'entreprise.",
      "bsonType": "number"
    }
  },
  "additionalProperties": false
}
`,
"ellisphere.schema.json": `{
  "title": "EntréeEllisphere",
  "description": "Champs importés par le parseur lib/ellisphere/main.go de sfdata.",
  "bsonType": "object",
  "properties": {
    "code_groupe": {
      "bsonType": "string"
    },
    "siren_groupe": {
      "bsonType": "string"
    },
    "refid_groupe": {
      "bsonType": "string"
    },
    "raison_sociale_groupe": {
      "bsonType": "string"
    },
    "adresse_groupe": {
      "bsonType": "string"
    },
    "personne_pou_m_groupe": {
      "bsonType": "string"
    },
    "niveau_detention": {
      "bsonType": "number"
    },
    "part_financiere": {
      "bsonType": "number"
    },
    "code_filiere": {
      "bsonType": "string"
    },
    "refid_filiere": {
      "bsonType": "string"
    },
    "personne_pou_m_filiere": {
      "bsonType": "string"
    }
  },
  "additionalProperties": false
}
`,
"flatten_data_entries.pipeline.json": `[
  { "$project": { "_id": 1, "batches": { "$objectToArray": "$value.batch" } } },
  { "$unwind": { "path": "$batches", "preserveNullAndEmptyArrays": false } },
  {
    "$project": {
      "_id": 1,
      "batchKey": "$batches.k",
      "dataPerHash": { "$objectToArray": "$batches.v" }
    }
  },
  {
    "$unwind": { "path": "$dataPerHash", "preserveNullAndEmptyArrays": false }
  },
  {
    "$project": {
      "_id": 1,
      "batchKey": 1,
      "dataType": "$dataPerHash.k",
      "dataPerHash": { "$objectToArray": "$dataPerHash.v" }
    }
  },
  {
    "$unwind": { "path": "$dataPerHash", "preserveNullAndEmptyArrays": false }
  },
  {
    "$project": {
      "_id": 1,
      "batchKey": 1,
      "dataType": 1,
      "dataHash": "$dataPerHash.k",
      "dataObject": "$dataPerHash.v"
    }
  }
]
`,
"paydex.schema.json": `{
  "title": "EntréePaydex",
  "description": "Champs importés par le parseur lib/paydex/main.go de sfdata.",
  "bsonType": "object",
  "required": ["date_valeur", "nb_jours"],
  "properties": {
    "date_valeur": {
      "bsonType": "date"
    },
    "nb_jours": {
      "bsonType": "number"
    }
  },
  "additionalProperties": false
}
`,
"procol.schema.json": `{
  "title": "EntréeDéfaillances",
  "description": "Champs importés par le parseur lib/urssaf/procol.go de sfdata.",
  "bsonType": "object",
  "required": ["action_procol", "stade_procol", "date_effet"],
  "properties": {
    "action_procol": {
      "description": "Nature de la procédure de défaillance.",
      "bsonType": "string",
      "enum": ["liquidation", "redressement", "sauvegarde"]
    },
    "stade_procol": {
      "description": "Evénement survenu dans le cadre de cette procédure.",
      "bsonType": "string",
      "enum": [
        "abandon_procedure",
        "solde_procedure",
        "fin_procedure",
        "plan_continuation",
        "ouverture",
        "inclusion_autre_procedure",
        "cloture_insuffisance_actif"
      ]
    },
    "date_effet": {
      "bsonType": "date",
      "description": "Date effet de la procédure collective."
    }
  },
  "additionalProperties": false
}
`,
"sirene.schema.json": `{
  "title": "EntréeSirene",
  "description": "Champs importés par le parseur lib/sirene/main.go de sfdata.",
  "bsonType": "object",
  "properties": {
    "siren": {
      "bsonType": "string"
    },
    "nic": {
      "bsonType": "string"
    },
    "siege": {
      "bsonType": "bool"
    },
    "complement_adresse": {
      "bsonType": "string"
    },
    "numero_voie": {
      "bsonType": "string"
    },
    "indrep": {
      "bsonType": "string"
    },
    "type_voie": {
      "bsonType": "string"
    },
    "voie": {
      "bsonType": "string"
    },
    "commune": {
      "bsonType": "string"
    },
    "commune_etranger": {
      "bsonType": "string"
    },
    "distribution_speciale": {
      "bsonType": "string"
    },
    "code_commune": {
      "bsonType": "string"
    },
    "code_cedex": {
      "bsonType": "string"
    },
    "cedex": {
      "bsonType": "string"
    },
    "code_pays_etranger": {
      "bsonType": "string"
    },
    "pays_etranger": {
      "bsonType": "string"
    },
    "code_postal": {
      "bsonType": "string"
    },
    "departement": {
      "bsonType": "string"
    },
    "ape": {
      "bsonType": "string"
    },
    "code_activite": {
      "bsonType": "string"
    },
    "nomen_activite": {
      "bsonType": "string"
    },
    "date_creation": {
      "bsonType": "date"
    },
    "longitude": {
      "bsonType": "number"
    },
    "latitude": {
      "bsonType": "number"
    }
  },
  "additionalProperties": false
}
`,
"sirene_ul.schema.json": `{
  "title": "EntréeSireneEntreprise",
  "description": "Champs importés par le parseur lib/sirene_ul/main.go de sfdata.",
  "bsonType": "object",
  "required": ["raison_sociale", "statut_juridique"],
  "properties": {
    "siren": {
      "bsonType": "string"
    },
    "nic": {
      "bsonType": "string"
    },
    "raison_sociale": {
      "bsonType": "string"
    },
    "nom_unite_legale": {
      "bsonType": "string"
    },
    "nom_usage_unite_legale": {
      "bsonType": "string"
    },
    "prenom1_unite_legale": {
      "bsonType": "string"
    },
    "prenom2_unite_legale": {
      "bsonType": "string"
    },
    "prenom3_unite_legale": {
      "bsonType": "string"
    },
    "prenom4_unite_legale": {
      "bsonType": "string"
    },
    "statut_juridique": {
      "description": "code numérique sérialisé en chaine de caractères",
      "bsonType": "string"
    },
    "date_creation": {
      "bsonType": "date"
    }
  },
  "additionalProperties": false
}
`,
}
