/* Generated by bundle-schemas.go - DO NOT EDIT */

package engine

var validationSchemas = map[string]string{
"bdf.schema.json": `{
  "title": "EntréeBdf",
  "description": "Note: CE SCHEMA EST INCOMPLET POUR L'INSTANT. Cf https://github.com/signaux-faibles/opensignauxfaibles/pull/143",
  "bsonType": "object",
  "required": ["siren"],
  "properties": {
    "siren": {
      "bsonType": "string",
      "pattern": "^[0-9]{9}$"
    }
  },
  "additionalProperties": false
}
`,
"ccsf.schema.json": `{
  "title": "EntréeCcsf",
  "description": "Champs importés par le parseur lib/urssaf/ccsf.go de sfdata.",
  "bsonType": "object",
  "required": ["date_traitement", "stade", "action"],
  "properties": {
    "date_traitement": {
      "bsonType": "date",
      "description": "Date de début de la procédure CCSF"
    },
    "stade": {
      "bsonType": "string",
      "description": "TODO: choisir un type plus précis"
    },
    "action": {
      "bsonType": "string",
      "description": "TODO: choisir un type plus précis"
    }
  },
  "additionalProperties": false
}
`,
"delai.schema.json": `{
  "title": "EntréeDelai",
  "description": "Champs importés par le parseur lib/urssaf/delai.go de sfdata.",
  "bsonType": "object",
  "required": [
    "numero_compte",
    "numero_contentieux",
    "date_creation",
    "date_echeance",
    "duree_delai",
    "denomination",
    "indic_6m",
    "annee_creation",
    "montant_echeancier",
    "stade",
    "action"
  ],
  "properties": {
    "numero_compte": {
      "bsonType": "string",
      "description": "Compte administratif URSSAF."
    },
    "numero_contentieux": {
      "bsonType": "string",
      "description": "Le numéro de structure est l'identifiant d'un dossier contentieux."
    },
    "date_creation": {
      "bsonType": "date",
      "description": "Date de création du délai."
    },
    "date_echeance": {
      "bsonType": "date",
      "description": "Date d'échéance du délai."
    },
    "duree_delai": {
      "bsonType": "number",
      "description": "Durée du délai en jours: nombre de jours entre date_creation et date_echeance.",
      "minimum": 1
    },
    "denomination": {
      "bsonType": "string",
      "description": "Raison sociale de l'établissement."
    },
    "indic_6m": {
      "bsonType": "string",
      "description": "Délai inférieur ou supérieur à 6 mois ? Modalités INF et SUP."
    },
    "annee_creation": {
      "bsonType": "number",
      "description": "Année de création du délai."
    },
    "montant_echeancier": {
      "bsonType": "number",
      "description": "Montant global de l'échéancier, en euros.",
      "minimum": 0.01
    },
    "stade": {
      "bsonType": "string",
      "description": "Code externe du stade."
    },
    "action": {
      "bsonType": "string",
      "description": "Code externe de l'action."
    }
  },
  "additionalProperties": false
}
`,
"detect_invalid_entries.pipeline.json": `[
  { "$project": { "_id": 1, "batches": { "$objectToArray": "$value.batch" } } },
  { "$unwind": { "path": "$batches", "preserveNullAndEmptyArrays": false } },
  {
    "$project": {
      "_id": 1,
      "batchKey": "$batches.k",
      "dataPerHash": { "$objectToArray": "$batches.v" }
    }
  },
  {
    "$unwind": { "path": "$dataPerHash", "preserveNullAndEmptyArrays": false }
  },
  {
    "$project": {
      "_id": 1,
      "batchKey": 1,
      "dataType": "$dataPerHash.k",
      "dataPerHash": "$dataPerHash.v"
    }
  },
  { "$match": { "dataPerHash": { "$not": { "$type": 3 } } } }
]
`,
"flatten_data_entries.pipeline.json": `[
  { "$project": { "_id": 1, "batches": { "$objectToArray": "$value.batch" } } },
  { "$unwind": { "path": "$batches", "preserveNullAndEmptyArrays": false } },
  {
    "$project": {
      "_id": 1,
      "batchKey": "$batches.k",
      "dataPerHash": { "$objectToArray": "$batches.v" }
    }
  },
  {
    "$unwind": { "path": "$dataPerHash", "preserveNullAndEmptyArrays": false }
  },
  {
    "$project": {
      "_id": 1,
      "batchKey": 1,
      "dataType": "$dataPerHash.k",
      "dataPerHash": { "$objectToArray": "$dataPerHash.v" }
    }
  },
  {
    "$unwind": { "path": "$dataPerHash", "preserveNullAndEmptyArrays": false }
  },
  {
    "$project": {
      "_id": 1,
      "batchKey": 1,
      "dataType": 1,
      "dataHash": "$dataPerHash.k",
      "dataObject": "$dataPerHash.v"
    }
  }
]
`,
"procol.schema.json": `{
  "title": "EntréeDéfaillances",
  "description": "Champs importés par le parseur lib/urssaf/procol.go de sfdata.",
  "bsonType": "object",
  "required": ["action_procol", "stade_procol", "date_effet"],
  "properties": {
    "action_procol": {
      "description": "Nature de la procédure de défaillance.",
      "bsonType": "string",
      "enum": ["liquidation", "redressement", "sauvegarde"]
    },
    "stade_procol": {
      "description": "Evénement survenu dans le cadre de cette procédure.",
      "bsonType": "string",
      "enum": [
        "abandon_procedure",
        "solde_procedure",
        "fin_procedure",
        "plan_continuation",
        "ouverture",
        "inclusion_autre_procedure",
        "cloture_insuffisance_actif"
      ]
    },
    "date_effet": {
      "bsonType": "date",
      "description": "Date effet de la procédure collective."
    }
  },
  "additionalProperties": false
}
`,
}
