/**
 * This file was automatically generated by generate-types.sh.
 *
 * DO NOT MODIFY IT BY HAND.
 *
 * Instead:
 * - modify the validation/*.schema.json files;
 * - then, run generate-types.sh to regenerate this file.
 */

export interface EntréeBdf {
  siren: string
  annee_bdf: number
  arrete_bilan_bdf: Date
  raison_sociale: string
  secteur: string
  poids_frng: number
  taux_marge: number
  delai_fournisseur: number
  dette_fiscale: number
  financier_court_terme: number
  frais_financier: number
}
export interface EntréeDelai {
  date_creation: Date
  date_echeance: Date
  /**
   * doit valoir 1 ou plus
   */
  duree_delai: number
  /**
   * doit valoir plus que 0 euros
   */
  montant_echeancier: number
}
