#!/bin/bash

OUT_FILE="GeneratedTypes.d.ts"

TS_TYPES=$(npx mongodb-json-schema-to-typescript --input "../validation/*.schema.json" --bannerComment '')

echo > "${OUT_FILE}" "\
/**
 * This file was automatically generated by generate-types.sh.
 * 
 * DO NOT MODIFY IT BY HAND.
 *
 * Instead:
 * - modify the validation/*.schema.json files;
 * - then, run generate-types.sh to regenerate this file.
 */

${TS_TYPES}"

$(npm bin)/eslint "${OUT_FILE}" --fix
