/**
 * This file was automatically generated by generate-types.sh.
 *
 * DO NOT MODIFY IT BY HAND.
 *
 * Instead:
 * - modify the validation/*.schema.json files;
 * - then, run generate-types.sh to regenerate this file.
 */

export interface EntréeBdf {
  siren: string
}
export interface EntréeDelai {
  date_creation: Date
  date_echeance: Date
  /**
   * Doit valoir 1 ou plus:
   */
  duree_delai: number
  /**
   * Doit valoir plus que 0 euros:
   */
  montant_echeancier: number
}
