CREATE TABLE categories_juridiques (
  code VARCHAR(10) PRIMARY KEY,
  libelle TEXT
);

INSERT INTO categories_juridiques(code,libelle) VALUES('0000','Organisme de placement collectif en valeurs mobilières sans personnalité morale');
INSERT INTO categories_juridiques(code,libelle) VALUES('1000','Entrepreneur individuel');
INSERT INTO categories_juridiques(code,libelle) VALUES('2110','Indivision entre personnes physiques');
INSERT INTO categories_juridiques(code,libelle) VALUES('2120','Indivision avec personne morale');
INSERT INTO categories_juridiques(code,libelle) VALUES('2210','Société créée de fait entre personnes physiques');
INSERT INTO categories_juridiques(code,libelle) VALUES('2220','Société créée de fait avec personne morale');
INSERT INTO categories_juridiques(code,libelle) VALUES('2310','Société en participation entre personnes physiques');
INSERT INTO categories_juridiques(code,libelle) VALUES('2320','Société en participation avec personne morale');
INSERT INTO categories_juridiques(code,libelle) VALUES('2385','Société en participation de professions libérales');
INSERT INTO categories_juridiques(code,libelle) VALUES('2400','Fiducie');
INSERT INTO categories_juridiques(code,libelle) VALUES('2700','Paroisse hors zone concordataire');
INSERT INTO categories_juridiques(code,libelle) VALUES('2800','Assujetti unique à la TVA');
INSERT INTO categories_juridiques(code,libelle) VALUES('2900','Autre groupement de droit privé non doté de la personnalité morale');
INSERT INTO categories_juridiques(code,libelle) VALUES('3110','Représentation ou agence commerciale d''état ou organisme public étranger immatriculé au RCS');
INSERT INTO categories_juridiques(code,libelle) VALUES('3120','Société commerciale étrangère immatriculée au RCS');
INSERT INTO categories_juridiques(code,libelle) VALUES('3205','Organisation internationale');
INSERT INTO categories_juridiques(code,libelle) VALUES('3210','État, collectivité ou établissement public étranger');
INSERT INTO categories_juridiques(code,libelle) VALUES('3220','Société étrangère non immatriculée au RCS');
INSERT INTO categories_juridiques(code,libelle) VALUES('3290','Autre personne morale de droit étranger');
INSERT INTO categories_juridiques(code,libelle) VALUES('4110','Établissement public national à caractère industriel ou commercial doté d''un comptable public');
INSERT INTO categories_juridiques(code,libelle) VALUES('4120','Établissement public national à caractère industriel ou commercial non doté d''un comptable public');
INSERT INTO categories_juridiques(code,libelle) VALUES('4130','Exploitant public');
INSERT INTO categories_juridiques(code,libelle) VALUES('4140','Établissement public local à caractère industriel ou commercial');
INSERT INTO categories_juridiques(code,libelle) VALUES('4150','Régie d''une collectivité locale à caractère industriel ou commercial');
INSERT INTO categories_juridiques(code,libelle) VALUES('4160','Institution Banque de France');
INSERT INTO categories_juridiques(code,libelle) VALUES('5191','Société de caution mutuelle');
INSERT INTO categories_juridiques(code,libelle) VALUES('5192','Société coopérative de banque populaire');
INSERT INTO categories_juridiques(code,libelle) VALUES('5193','Caisse de crédit maritime mutuel');
INSERT INTO categories_juridiques(code,libelle) VALUES('5194','Caisse (fédérale) de crédit mutuel');
INSERT INTO categories_juridiques(code,libelle) VALUES('5195','Association coopérative inscrite (droit local Alsace Moselle)');
INSERT INTO categories_juridiques(code,libelle) VALUES('5196','Caisse d''épargne et de prévoyance à forme coopérative');
INSERT INTO categories_juridiques(code,libelle) VALUES('5202','Société en nom collectif');
INSERT INTO categories_juridiques(code,libelle) VALUES('5203','Société en nom collectif coopérative');
INSERT INTO categories_juridiques(code,libelle) VALUES('5306','Société en commandite simple');
INSERT INTO categories_juridiques(code,libelle) VALUES('5307','Société en commandite simple coopérative');
INSERT INTO categories_juridiques(code,libelle) VALUES('5308','Société en commandite par actions');
INSERT INTO categories_juridiques(code,libelle) VALUES('5309','Société en commandite par actions coopérative');
INSERT INTO categories_juridiques(code,libelle) VALUES('5310','Société en libre partenariat (SLP)');
INSERT INTO categories_juridiques(code,libelle) VALUES('5370','Société de Participations Financières de Profession Libérale Société en commandite par actions (SPFPL SCA)');
INSERT INTO categories_juridiques(code,libelle) VALUES('5385','Société d''exercice libéral en commandite par actions');
INSERT INTO categories_juridiques(code,libelle) VALUES('5410','SARL nationale');
INSERT INTO categories_juridiques(code,libelle) VALUES('5415','SARL d''économie mixte');
INSERT INTO categories_juridiques(code,libelle) VALUES('5422','SARL immobilière pour le commerce et l''industrie (SICOMI)');
INSERT INTO categories_juridiques(code,libelle) VALUES('5426','SARL immobilière de gestion');
INSERT INTO categories_juridiques(code,libelle) VALUES('5430','SARL d''aménagement foncier et d''équipement rural (SAFER)');
INSERT INTO categories_juridiques(code,libelle) VALUES('5431','SARL mixte d''intérêt agricole (SMIA)');
INSERT INTO categories_juridiques(code,libelle) VALUES('5432','SARL d''intérêt collectif agricole (SICA)');
INSERT INTO categories_juridiques(code,libelle) VALUES('5442','SARL d''attribution');
INSERT INTO categories_juridiques(code,libelle) VALUES('5443','SARL coopérative de construction');
INSERT INTO categories_juridiques(code,libelle) VALUES('5451','SARL coopérative de consommation');
INSERT INTO categories_juridiques(code,libelle) VALUES('5453','SARL coopérative artisanale');
INSERT INTO categories_juridiques(code,libelle) VALUES('5454','SARL coopérative d''intérêt maritime');
INSERT INTO categories_juridiques(code,libelle) VALUES('5455','SARL coopérative de transport');
INSERT INTO categories_juridiques(code,libelle) VALUES('5458','SARL coopérative de production (SCOP)');
INSERT INTO categories_juridiques(code,libelle) VALUES('5459','SARL union de sociétés coopératives');
INSERT INTO categories_juridiques(code,libelle) VALUES('5460','Autre SARL coopérative');
INSERT INTO categories_juridiques(code,libelle) VALUES('5470','Société de Participations Financières de Profession Libérale Société à responsabilité limitée (SPFPL SARL)');
INSERT INTO categories_juridiques(code,libelle) VALUES('5485','Société d''exercice libéral à responsabilité limitée');
INSERT INTO categories_juridiques(code,libelle) VALUES('5499','Société à responsabilité limitée (sans autre indication)');
INSERT INTO categories_juridiques(code,libelle) VALUES('5505','SA à participation ouvrière à conseil d''administration');
INSERT INTO categories_juridiques(code,libelle) VALUES('5510','SA nationale à conseil d''administration');
INSERT INTO categories_juridiques(code,libelle) VALUES('5515','SA d''économie mixte à conseil d''administration');
INSERT INTO categories_juridiques(code,libelle) VALUES('5520','Fonds à forme sociétale à conseil d''administration');
INSERT INTO categories_juridiques(code,libelle) VALUES('5522','SA immobilière pour le commerce et l''industrie (SICOMI) à conseil d''administration');
INSERT INTO categories_juridiques(code,libelle) VALUES('5525','SA immobilière d''investissement à conseil d''administration');
INSERT INTO categories_juridiques(code,libelle) VALUES('5530','SA d''aménagement foncier et d''équipement rural (SAFER) à conseil d''administration');
INSERT INTO categories_juridiques(code,libelle) VALUES('5531','Société anonyme mixte d''intérêt agricole (SMIA) à conseil d''administration');
INSERT INTO categories_juridiques(code,libelle) VALUES('5532','SA d''intérêt collectif agricole (SICA) à conseil d''administration');
INSERT INTO categories_juridiques(code,libelle) VALUES('5542','SA d''attribution à conseil d''administration');
INSERT INTO categories_juridiques(code,libelle) VALUES('5543','SA coopérative de construction à conseil d''administration');
INSERT INTO categories_juridiques(code,libelle) VALUES('5546','SA de HLM à conseil d''administration');
INSERT INTO categories_juridiques(code,libelle) VALUES('5547','SA coopérative de production de HLM à conseil d''administration');
INSERT INTO categories_juridiques(code,libelle) VALUES('5548','SA de crédit immobilier à conseil d''administration');
INSERT INTO categories_juridiques(code,libelle) VALUES('5551','SA coopérative de consommation à conseil d''administration');
INSERT INTO categories_juridiques(code,libelle) VALUES('5552','SA coopérative de commerçants-détaillants à conseil d''administration');
INSERT INTO categories_juridiques(code,libelle) VALUES('5553','SA coopérative artisanale à conseil d''administration');
INSERT INTO categories_juridiques(code,libelle) VALUES('5554','SA coopérative (d''intérêt) maritime à conseil d''administration');
INSERT INTO categories_juridiques(code,libelle) VALUES('5555','SA coopérative de transport à conseil d''administration');
INSERT INTO categories_juridiques(code,libelle) VALUES('5558','SA coopérative de production  (SCOP) à conseil d''administration');
INSERT INTO categories_juridiques(code,libelle) VALUES('5559','SA union de sociétés coopératives à conseil d''administration');
INSERT INTO categories_juridiques(code,libelle) VALUES('5560','Autre SA coopérative à conseil d''administration');
INSERT INTO categories_juridiques(code,libelle) VALUES('5570','Société de Participations Financières de Profession Libérale Société anonyme à conseil d''administration (SPFPL SA à conseil d''administration)');
INSERT INTO categories_juridiques(code,libelle) VALUES('5585','Société d''exercice libéral à forme anonyme à conseil d''administration');
INSERT INTO categories_juridiques(code,libelle) VALUES('5599','SA à conseil d''administration (s.a.i.)');
INSERT INTO categories_juridiques(code,libelle) VALUES('5605','SA à participation ouvrière à directoire');
INSERT INTO categories_juridiques(code,libelle) VALUES('5610','SA nationale à directoire');
INSERT INTO categories_juridiques(code,libelle) VALUES('5615','SA d''économie mixte à directoire');
INSERT INTO categories_juridiques(code,libelle) VALUES('5620','Fonds à forme sociétale à directoire');
INSERT INTO categories_juridiques(code,libelle) VALUES('5622','SA immobilière pour le commerce et l''industrie (SICOMI) à directoire');
INSERT INTO categories_juridiques(code,libelle) VALUES('5625','SA immobilière d''investissement à directoire');
INSERT INTO categories_juridiques(code,libelle) VALUES('5630','Safer anonyme à directoire');
INSERT INTO categories_juridiques(code,libelle) VALUES('5631','SA mixte d''intérêt agricole (SMIA)');
INSERT INTO categories_juridiques(code,libelle) VALUES('5632','SA d''intérêt collectif agricole (SICA)');
INSERT INTO categories_juridiques(code,libelle) VALUES('5642','SA d''attribution à directoire');
INSERT INTO categories_juridiques(code,libelle) VALUES('5643','SA coopérative de construction à directoire');
INSERT INTO categories_juridiques(code,libelle) VALUES('5646','SA de HLM à directoire');
INSERT INTO categories_juridiques(code,libelle) VALUES('5647','Société coopérative de production de HLM anonyme à directoire');
INSERT INTO categories_juridiques(code,libelle) VALUES('5648','SA de crédit immobilier à directoire');
INSERT INTO categories_juridiques(code,libelle) VALUES('5651','SA coopérative de consommation à directoire');
INSERT INTO categories_juridiques(code,libelle) VALUES('5652','SA coopérative de commerçants-détaillants à directoire');
INSERT INTO categories_juridiques(code,libelle) VALUES('5653','SA coopérative artisanale à directoire');
INSERT INTO categories_juridiques(code,libelle) VALUES('5654','SA coopérative d''intérêt maritime à directoire');
INSERT INTO categories_juridiques(code,libelle) VALUES('5655','SA coopérative de transport à directoire');
INSERT INTO categories_juridiques(code,libelle) VALUES('5658','SA coopérative de production (SCOP) à directoire');
INSERT INTO categories_juridiques(code,libelle) VALUES('5659','SA union de sociétés coopératives à directoire');
INSERT INTO categories_juridiques(code,libelle) VALUES('5660','Autre SA coopérative à directoire');
INSERT INTO categories_juridiques(code,libelle) VALUES('5670','Société de Participations Financières de Profession Libérale Société anonyme à Directoire (SPFPL SA à directoire)');
INSERT INTO categories_juridiques(code,libelle) VALUES('5685','Société d''exercice libéral à forme anonyme à directoire');
INSERT INTO categories_juridiques(code,libelle) VALUES('5699','SA à directoire (s.a.i.)');
INSERT INTO categories_juridiques(code,libelle) VALUES('5710','SAS, société par actions simplifiée');
INSERT INTO categories_juridiques(code,libelle) VALUES('5770','Société de Participations Financières de Profession Libérale Société par actions simplifiée (SPFPL SAS)');
INSERT INTO categories_juridiques(code,libelle) VALUES('5785','Société d''exercice libéral par action simplifiée');
INSERT INTO categories_juridiques(code,libelle) VALUES('5800','Société européenne');
INSERT INTO categories_juridiques(code,libelle) VALUES('6100','Caisse d''Épargne et de Prévoyance');
INSERT INTO categories_juridiques(code,libelle) VALUES('6210','Groupement européen d''intérêt économique (GEIE)');
INSERT INTO categories_juridiques(code,libelle) VALUES('6220','Groupement d''intérêt économique (GIE)');
INSERT INTO categories_juridiques(code,libelle) VALUES('6316','Coopérative d''utilisation de matériel agricole en commun (CUMA)');
INSERT INTO categories_juridiques(code,libelle) VALUES('6317','Société coopérative agricole');
INSERT INTO categories_juridiques(code,libelle) VALUES('6318','Union de sociétés coopératives agricoles');
INSERT INTO categories_juridiques(code,libelle) VALUES('6411','Société d''assurance à forme mutuelle');
INSERT INTO categories_juridiques(code,libelle) VALUES('6511','Sociétés Interprofessionnelles de Soins Ambulatoires ');
INSERT INTO categories_juridiques(code,libelle) VALUES('6521','Société civile de placement collectif immobilier (SCPI)');
INSERT INTO categories_juridiques(code,libelle) VALUES('6532','Société civile d''intérêt collectif agricole (SICA)');
INSERT INTO categories_juridiques(code,libelle) VALUES('6533','Groupement agricole d''exploitation en commun (GAEC)');
INSERT INTO categories_juridiques(code,libelle) VALUES('6534','Groupement foncier agricole');
INSERT INTO categories_juridiques(code,libelle) VALUES('6535','Groupement agricole foncier');
INSERT INTO categories_juridiques(code,libelle) VALUES('6536','Groupement forestier');
INSERT INTO categories_juridiques(code,libelle) VALUES('6537','Groupement pastoral');
INSERT INTO categories_juridiques(code,libelle) VALUES('6538','Groupement foncier et rural');
INSERT INTO categories_juridiques(code,libelle) VALUES('6539','Société civile foncière');
INSERT INTO categories_juridiques(code,libelle) VALUES('6540','Société civile immobilière');
INSERT INTO categories_juridiques(code,libelle) VALUES('6541','Société civile immobilière de construction-vente');
INSERT INTO categories_juridiques(code,libelle) VALUES('6542','Société civile d''attribution');
INSERT INTO categories_juridiques(code,libelle) VALUES('6543','Société civile coopérative de construction');
INSERT INTO categories_juridiques(code,libelle) VALUES('6544','Société civile immobilière d'' accession progressive à la propriété');
INSERT INTO categories_juridiques(code,libelle) VALUES('6551','Société civile coopérative de consommation');
INSERT INTO categories_juridiques(code,libelle) VALUES('6554','Société civile coopérative d''intérêt maritime');
INSERT INTO categories_juridiques(code,libelle) VALUES('6558','Société civile coopérative entre médecins');
INSERT INTO categories_juridiques(code,libelle) VALUES('6560','Autre société civile coopérative');
INSERT INTO categories_juridiques(code,libelle) VALUES('6561','SCP d''avocats');
INSERT INTO categories_juridiques(code,libelle) VALUES('6562','SCP d''avocats aux conseils');
INSERT INTO categories_juridiques(code,libelle) VALUES('6563','SCP d''avoués d''appel');
INSERT INTO categories_juridiques(code,libelle) VALUES('6564','SCP d''huissiers');
INSERT INTO categories_juridiques(code,libelle) VALUES('6565','SCP de notaires');
INSERT INTO categories_juridiques(code,libelle) VALUES('6566','SCP de commissaires-priseurs');
INSERT INTO categories_juridiques(code,libelle) VALUES('6567','SCP de greffiers de tribunal de commerce');
INSERT INTO categories_juridiques(code,libelle) VALUES('6568','SCP de conseils juridiques');
INSERT INTO categories_juridiques(code,libelle) VALUES('6569','SCP de commissaires aux comptes');
INSERT INTO categories_juridiques(code,libelle) VALUES('6571','SCP de médecins');
INSERT INTO categories_juridiques(code,libelle) VALUES('6572','SCP de dentistes');
INSERT INTO categories_juridiques(code,libelle) VALUES('6573','SCP d''infirmiers');
INSERT INTO categories_juridiques(code,libelle) VALUES('6574','SCP de masseurs-kinésithérapeutes');
INSERT INTO categories_juridiques(code,libelle) VALUES('6575','SCP de directeurs de laboratoire d''analyse médicale');
INSERT INTO categories_juridiques(code,libelle) VALUES('6576','SCP de vétérinaires');
INSERT INTO categories_juridiques(code,libelle) VALUES('6577','SCP de géomètres experts');
INSERT INTO categories_juridiques(code,libelle) VALUES('6578','SCP d''architectes');
INSERT INTO categories_juridiques(code,libelle) VALUES('6585','Autre société civile professionnelle');
INSERT INTO categories_juridiques(code,libelle) VALUES('6589','Société civile de moyens');
INSERT INTO categories_juridiques(code,libelle) VALUES('6595','Caisse locale de crédit mutuel');
INSERT INTO categories_juridiques(code,libelle) VALUES('6596','Caisse de crédit agricole mutuel');
INSERT INTO categories_juridiques(code,libelle) VALUES('6597','Société civile d''exploitation agricole');
INSERT INTO categories_juridiques(code,libelle) VALUES('6598','Exploitation agricole à responsabilité limitée');
INSERT INTO categories_juridiques(code,libelle) VALUES('6599','Autre société civile');
INSERT INTO categories_juridiques(code,libelle) VALUES('6901','Autre personne de droit privé inscrite au registre du commerce et des sociétés');
INSERT INTO categories_juridiques(code,libelle) VALUES('7111','Autorité constitutionnelle');
INSERT INTO categories_juridiques(code,libelle) VALUES('7112','Autorité administrative ou publique indépendante');
INSERT INTO categories_juridiques(code,libelle) VALUES('7113','Ministère');
INSERT INTO categories_juridiques(code,libelle) VALUES('7120','Service central d''un ministère');
INSERT INTO categories_juridiques(code,libelle) VALUES('7150','Service du ministère de la Défense');
INSERT INTO categories_juridiques(code,libelle) VALUES('7160','Service déconcentré à compétence nationale d''un ministère (hors Défense)');
INSERT INTO categories_juridiques(code,libelle) VALUES('7171','Service déconcentré de l''État à compétence (inter) régionale');
INSERT INTO categories_juridiques(code,libelle) VALUES('7172','Service déconcentré de l''État à compétence (inter) départementale');
INSERT INTO categories_juridiques(code,libelle) VALUES('7179','(Autre) Service déconcentré de l''État à compétence territoriale');
INSERT INTO categories_juridiques(code,libelle) VALUES('7190','Ecole nationale non dotée de la personnalité morale');
INSERT INTO categories_juridiques(code,libelle) VALUES('7210','Commune et commune nouvelle');
INSERT INTO categories_juridiques(code,libelle) VALUES('7220','Département');
INSERT INTO categories_juridiques(code,libelle) VALUES('7225','Collectivité et territoire d''Outre Mer');
INSERT INTO categories_juridiques(code,libelle) VALUES('7229','(Autre) Collectivité territoriale');
INSERT INTO categories_juridiques(code,libelle) VALUES('7230','Région');
INSERT INTO categories_juridiques(code,libelle) VALUES('7312','Commune associée et commune déléguée');
INSERT INTO categories_juridiques(code,libelle) VALUES('7313','Section de commune');
INSERT INTO categories_juridiques(code,libelle) VALUES('7314','Ensemble urbain');
INSERT INTO categories_juridiques(code,libelle) VALUES('7321','Association syndicale autorisée');
INSERT INTO categories_juridiques(code,libelle) VALUES('7322','Association foncière urbaine');
INSERT INTO categories_juridiques(code,libelle) VALUES('7323','Association foncière de remembrement');
INSERT INTO categories_juridiques(code,libelle) VALUES('7331','Établissement public local d''enseignement');
INSERT INTO categories_juridiques(code,libelle) VALUES('7340','Pôle métropolitain');
INSERT INTO categories_juridiques(code,libelle) VALUES('7341','Secteur de commune');
INSERT INTO categories_juridiques(code,libelle) VALUES('7342','District urbain');
INSERT INTO categories_juridiques(code,libelle) VALUES('7343','Communauté urbaine');
INSERT INTO categories_juridiques(code,libelle) VALUES('7344','Métropole');
INSERT INTO categories_juridiques(code,libelle) VALUES('7345','Syndicat intercommunal à vocation multiple (SIVOM)');
INSERT INTO categories_juridiques(code,libelle) VALUES('7346','Communauté de communes');
INSERT INTO categories_juridiques(code,libelle) VALUES('7347','Communauté de villes');
INSERT INTO categories_juridiques(code,libelle) VALUES('7348','Communauté d''agglomération');
INSERT INTO categories_juridiques(code,libelle) VALUES('7349','Autre établissement public local de coopération non spécialisé ou entente');
INSERT INTO categories_juridiques(code,libelle) VALUES('7351','Institution interdépartementale ou entente');
INSERT INTO categories_juridiques(code,libelle) VALUES('7352','Institution interrégionale ou entente');
INSERT INTO categories_juridiques(code,libelle) VALUES('7353','Syndicat intercommunal à vocation unique (SIVU)');
INSERT INTO categories_juridiques(code,libelle) VALUES('7354','Syndicat mixte fermé');
INSERT INTO categories_juridiques(code,libelle) VALUES('7355','Syndicat mixte ouvert');
INSERT INTO categories_juridiques(code,libelle) VALUES('7356','Commission syndicale pour la gestion des biens indivis des communes');
INSERT INTO categories_juridiques(code,libelle) VALUES('7357','Pôle d''équilibre territorial et rural (PETR)');
INSERT INTO categories_juridiques(code,libelle) VALUES('7361','Centre communal d''action sociale');
INSERT INTO categories_juridiques(code,libelle) VALUES('7362','Caisse des écoles');
INSERT INTO categories_juridiques(code,libelle) VALUES('7363','Caisse de crédit municipal');
INSERT INTO categories_juridiques(code,libelle) VALUES('7364','Établissement d''hospitalisation');
INSERT INTO categories_juridiques(code,libelle) VALUES('7365','Syndicat inter hospitalier');
INSERT INTO categories_juridiques(code,libelle) VALUES('7366','Établissement public local social et médico-social');
INSERT INTO categories_juridiques(code,libelle) VALUES('7367','Centre Intercommunal d''action sociale (CIAS)');
INSERT INTO categories_juridiques(code,libelle) VALUES('7371','Office public d''habitation à loyer modéré (OPHLM)');
INSERT INTO categories_juridiques(code,libelle) VALUES('7372','Service départemental d''incendie et de secours (SDIS)');
INSERT INTO categories_juridiques(code,libelle) VALUES('7373','Établissement public local culturel');
INSERT INTO categories_juridiques(code,libelle) VALUES('7378','Régie d''une collectivité locale à caractère administratif');
INSERT INTO categories_juridiques(code,libelle) VALUES('7379','(Autre) Établissement public administratif local');
INSERT INTO categories_juridiques(code,libelle) VALUES('7381','Organisme consulaire');
INSERT INTO categories_juridiques(code,libelle) VALUES('7382','Établissement public national ayant fonction d''administration centrale');
INSERT INTO categories_juridiques(code,libelle) VALUES('7383','Établissement public national à caractère scientifique culturel et professionnel');
INSERT INTO categories_juridiques(code,libelle) VALUES('7384','Autre établissement public national d''enseignement');
INSERT INTO categories_juridiques(code,libelle) VALUES('7385','Autre établissement public national administratif à compétence territoriale limitée');
INSERT INTO categories_juridiques(code,libelle) VALUES('7389','Établissement public national à caractère administratif');
INSERT INTO categories_juridiques(code,libelle) VALUES('7410','Groupement d''intérêt public (GIP)');
INSERT INTO categories_juridiques(code,libelle) VALUES('7430','Établissement public des cultes d''Alsace-Lorraine');
INSERT INTO categories_juridiques(code,libelle) VALUES('7450','Etablissement public administratif, cercle et foyer dans les armées');
INSERT INTO categories_juridiques(code,libelle) VALUES('7470','Groupement de coopération sanitaire à gestion publique');
INSERT INTO categories_juridiques(code,libelle) VALUES('7490','Autre personne morale de droit administratif');
INSERT INTO categories_juridiques(code,libelle) VALUES('8110','Régime général de la Sécurité Sociale');
INSERT INTO categories_juridiques(code,libelle) VALUES('8120','Régime spécial de Sécurité Sociale');
INSERT INTO categories_juridiques(code,libelle) VALUES('8130','Institution de retraite complémentaire');
INSERT INTO categories_juridiques(code,libelle) VALUES('8140','Mutualité sociale agricole');
INSERT INTO categories_juridiques(code,libelle) VALUES('8150','Régime maladie des non-salariés non agricoles');
INSERT INTO categories_juridiques(code,libelle) VALUES('8160','Régime vieillesse ne dépendant pas du régime général de la Sécurité Sociale');
INSERT INTO categories_juridiques(code,libelle) VALUES('8170','Régime d''assurance chômage');
INSERT INTO categories_juridiques(code,libelle) VALUES('8190','Autre régime de prévoyance sociale');
INSERT INTO categories_juridiques(code,libelle) VALUES('8210','Mutuelle');
INSERT INTO categories_juridiques(code,libelle) VALUES('8250','Assurance mutuelle agricole');
INSERT INTO categories_juridiques(code,libelle) VALUES('8290','Autre organisme mutualiste');
INSERT INTO categories_juridiques(code,libelle) VALUES('8310','Comité social économique d’entreprise');
INSERT INTO categories_juridiques(code,libelle) VALUES('8311','Comité social économique d''établissement');
INSERT INTO categories_juridiques(code,libelle) VALUES('8410','Syndicat de salariés');
INSERT INTO categories_juridiques(code,libelle) VALUES('8420','Syndicat patronal');
INSERT INTO categories_juridiques(code,libelle) VALUES('8450','Ordre professionnel ou assimilé');
INSERT INTO categories_juridiques(code,libelle) VALUES('8470','Centre technique industriel ou comité professionnel du développement économique');
INSERT INTO categories_juridiques(code,libelle) VALUES('8490','Autre organisme professionnel');
INSERT INTO categories_juridiques(code,libelle) VALUES('8510','Institution de prévoyance');
INSERT INTO categories_juridiques(code,libelle) VALUES('8520','Institution de retraite supplémentaire');
INSERT INTO categories_juridiques(code,libelle) VALUES('9110','Syndicat de copropriété');
INSERT INTO categories_juridiques(code,libelle) VALUES('9150','Association syndicale libre');
INSERT INTO categories_juridiques(code,libelle) VALUES('9210','Association non déclarée');
INSERT INTO categories_juridiques(code,libelle) VALUES('9220','Association déclarée');
INSERT INTO categories_juridiques(code,libelle) VALUES('9221','Association déclarée d''insertion par l''économique');
INSERT INTO categories_juridiques(code,libelle) VALUES('9222','Association intermédiaire');
INSERT INTO categories_juridiques(code,libelle) VALUES('9223','Groupement d''employeurs');
INSERT INTO categories_juridiques(code,libelle) VALUES('9224','Association d''avocats à responsabilité professionnelle individuelle');
INSERT INTO categories_juridiques(code,libelle) VALUES('9230','Association déclarée, reconnue d''utilité publique');
INSERT INTO categories_juridiques(code,libelle) VALUES('9240','Congrégation');
INSERT INTO categories_juridiques(code,libelle) VALUES('9260','Association de droit local (Bas-Rhin, Haut-Rhin et Moselle)');
INSERT INTO categories_juridiques(code,libelle) VALUES('9300','Fondation');
INSERT INTO categories_juridiques(code,libelle) VALUES('9900','Autre personne morale de droit privé');
INSERT INTO categories_juridiques(code,libelle) VALUES('9970','Groupement de coopération sanitaire à gestion privée');

---- create above / drop below ----

DROP TABLE categories_juridiques;
