CREATE TABLE IF NOT EXISTS naf25_codes (
    niv5         VARCHAR(10) PRIMARY KEY,
    niv4         VARCHAR(10),
    niv3         VARCHAR(10),
    niv2         VARCHAR(10),
    niv1         VARCHAR(1),
    niv1_libelle TEXT,
    niv5_libelle TEXT
    );

CREATE INDEX IF NOT EXISTS idx_naf25_codes_niv5 ON naf25_codes(niv5);
CREATE INDEX IF NOT EXISTS idx_naf25_codes_niv1 ON naf25_codes(niv1);

INSERT INTO naf25_codes (niv5, niv4, niv3, niv2, niv1, niv1_libelle, niv5_libelle) VALUES
  ('01.11Y', '01.11', '01.1', '01', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Culture de céréales, à l''exception du riz, de légumineuses et de graines oléagineuses'),
  ('01.12Y', '01.12', '01.1', '01', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Culture du riz'),
  ('01.13Y', '01.13', '01.1', '01', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Culture de légumes, de melons, de racines et de tubercules'),
  ('01.14Y', '01.14', '01.1', '01', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Culture de la canne à sucre'),
  ('01.15Y', '01.15', '01.1', '01', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Culture du tabac'),
  ('01.16Y', '01.16', '01.1', '01', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Culture de plantes à fibres'),
  ('01.19Y', '01.19', '01.1', '01', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Autres cultures non permanentes'),
  ('01.21Y', '01.21', '01.2', '01', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Culture de la vigne'),
  ('01.22Y', '01.22', '01.2', '01', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Culture de fruits tropicaux et subtropicaux'),
  ('01.23Y', '01.23', '01.2', '01', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Culture d''agrumes'),
  ('01.24Y', '01.24', '01.2', '01', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Culture de fruits à pépins et à noyau'),
  ('01.25Y', '01.25', '01.2', '01', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Culture d''autres fruits d''arbres ou d''arbustes et de fruits à coque'),
  ('01.26Y', '01.26', '01.2', '01', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Culture de fruits oléagineux'),
  ('01.27Y', '01.27', '01.2', '01', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Culture de plantes à boissons'),
  ('01.28Y', '01.28', '01.2', '01', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Culture de plantes à épices, aromatiques, médicinales et pharmaceutiques'),
  ('01.29Y', '01.29', '01.2', '01', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Autres cultures permanentes'),
  ('01.30Y', '01.30', '01.3', '01', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Reproduction de plantes'),
  ('01.41Y', '01.41', '01.4', '01', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Élevage de vaches laitières'),
  ('01.42Y', '01.42', '01.4', '01', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Élevage d''autres bovins et de buffles'),
  ('01.43Y', '01.43', '01.4', '01', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Élevage de chevaux et d''autres équidés'),
  ('01.44Y', '01.44', '01.4', '01', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Élevage de chameaux et d''autres camélidés'),
  ('01.45Y', '01.45', '01.4', '01', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Élevage d''ovins et de caprins'),
  ('01.46Y', '01.46', '01.4', '01', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Élevage de porcins'),
  ('01.47Y', '01.47', '01.4', '01', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Élevage de volailles'),
  ('01.48G', '01.48', '01.4', '01', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Apiculture'),
  ('01.48H', '01.48', '01.4', '01', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Élevage d''autres animaux destinés à la consommation'),
  ('01.48J', '01.48', '01.4', '01', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Élevage d''animaux de compagnie et d''autres animaux n.c.a.'),
  ('01.50Y', '01.50', '01.5', '01', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Culture et élevage associés'),
  ('01.61Y', '01.61', '01.6', '01', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Activités de soutien aux cultures'),
  ('01.62Y', '01.62', '01.6', '01', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Activités de soutien à la production animale'),
  ('01.63Y', '01.63', '01.6', '01', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Traitement primaire des récoltes et traitement des semences'),
  ('01.70Y', '01.70', '01.7', '01', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Chasse, piégeage et activités de service connexes'),
  ('02.10Y', '02.10', '02.1', '02', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Sylviculture et autres activités forestières'),
  ('02.20Y', '02.20', '02.2', '02', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Exploitation forestière'),
  ('02.30Y', '02.30', '02.3', '02', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Récolte de produits forestiers non ligneux poussant à l''état sauvage'),
  ('02.40Y', '02.40', '02.4', '02', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Activités de soutien à l''exploitation forestière'),
  ('03.11Y', '03.11', '03.1', '03', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Pêche en mer'),
  ('03.12Y', '03.12', '03.1', '03', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Pêche en eau douce'),
  ('03.21Y', '03.21', '03.2', '03', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Aquaculture en mer'),
  ('03.22Y', '03.22', '03.2', '03', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Aquaculture en eau douce'),
  ('03.30Y', '03.30', '03.3', '03', 'A', 'AGRICULTURE, SYLVICULTURE ET PÊCHE', 'Activités de soutien à la pêche et l''aquaculture'),
  ('05.10Y', '05.10', '05.1', '05', 'B', 'INDUSTRIES EXTRACTIVES', 'Extraction de houille'),
  ('05.20Y', '05.20', '05.2', '05', 'B', 'INDUSTRIES EXTRACTIVES', 'Extraction de lignite'),
  ('06.10Y', '06.10', '06.1', '06', 'B', 'INDUSTRIES EXTRACTIVES', 'Extraction de pétrole brut'),
  ('06.20Y', '06.20', '06.2', '06', 'B', 'INDUSTRIES EXTRACTIVES', 'Extraction de gaz naturel'),
  ('07.10Y', '07.10', '07.1', '07', 'B', 'INDUSTRIES EXTRACTIVES', 'Extraction de minerais de fer'),
  ('07.21Y', '07.21', '07.2', '07', 'B', 'INDUSTRIES EXTRACTIVES', 'Extraction de minerais d''uranium et de thorium'),
  ('07.29Y', '07.29', '07.2', '07', 'B', 'INDUSTRIES EXTRACTIVES', 'Extraction d''autres minerais de métaux non ferreux'),
  ('08.11Y', '08.11', '08.1', '08', 'B', 'INDUSTRIES EXTRACTIVES', 'Extraction de pierres ornementales, de calcaire industriel, de gypse, d''ardoise et d''autres pierres'),
  ('08.12Y', '08.12', '08.1', '08', 'B', 'INDUSTRIES EXTRACTIVES', 'Exploitation de gravières et sablières, extraction d''argiles et de kaolin'),
  ('08.91Y', '08.91', '08.9', '08', 'B', 'INDUSTRIES EXTRACTIVES', 'Extraction de minéraux chimiques et d''engrais minéraux'),
  ('08.92Y', '08.92', '08.9', '08', 'B', 'INDUSTRIES EXTRACTIVES', 'Extraction de tourbe'),
  ('08.93Y', '08.93', '08.9', '08', 'B', 'INDUSTRIES EXTRACTIVES', 'Production de sel'),
  ('08.99Y', '08.99', '08.9', '08', 'B', 'INDUSTRIES EXTRACTIVES', 'Autres activités extractives n.c.a.'),
  ('09.10Y', '09.10', '09.1', '09', 'B', 'INDUSTRIES EXTRACTIVES', 'Activités de soutien à l''extraction d''hydrocarbures'),
  ('09.90Y', '09.90', '09.9', '09', 'B', 'INDUSTRIES EXTRACTIVES', 'Activités de soutien aux autres industries extractives'),
  ('10.11Y', '10.11', '10.1', '10', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Transformation et conservation de la viande, à l''exception de la viande de volaille'),
  ('10.12Y', '10.12', '10.1', '10', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Transformation et conservation de la viande de volaille'),
  ('10.13G', '10.13', '10.1', '10', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Préparation industrielle de produits à base de viande'),
  ('10.13H', '10.13', '10.1', '10', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Préparation de produits à base de viande associée à leur vente au détail'),
  ('10.20Y', '10.20', '10.2', '10', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Transformation et conservation de poisson, de crustacés et de mollusques'),
  ('10.31Y', '10.31', '10.3', '10', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Transformation et conservation de pommes de terre'),
  ('10.32Y', '10.32', '10.3', '10', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Préparation de jus de fruits et légumes'),
  ('10.39G', '10.39', '10.3', '10', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Autre transformation et conservation de légumes'),
  ('10.39H', '10.39', '10.3', '10', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Autre transformation et conservation de fruits'),
  ('10.41Y', '10.41', '10.4', '10', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''huiles et graisses'),
  ('10.42Y', '10.42', '10.4', '10', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de margarine et graisses comestibles similaires'),
  ('10.51G', '10.51', '10.5', '10', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de lait liquide, crèmes de lait et laits fermentés'),
  ('10.51H', '10.51', '10.5', '10', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de fromage'),
  ('10.51J', '10.51', '10.5', '10', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de beurre et d''autres produits laitiers'),
  ('10.52Y', '10.52', '10.5', '10', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de crèmes glacées et autres glaces alimentaires'),
  ('10.61G', '10.61', '10.6', '10', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Meunerie'),
  ('10.61H', '10.61', '10.6', '10', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Autres activités du travail des grains'),
  ('10.62Y', '10.62', '10.6', '10', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de produits amylacés'),
  ('10.71G', '10.71', '10.7', '10', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication industrielle de pain et de pâtisserie fraîche'),
  ('10.71H', '10.71', '10.7', '10', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de pain et d''autres produits de boulangerie-pâtisserie associée à leur vente au détail'),
  ('10.71J', '10.71', '10.7', '10', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de pâtisserie fraîche associée à sa vente au détail'),
  ('10.72Y', '10.72', '10.7', '10', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de biscuits, biscottes et pâtisseries de conservation'),
  ('10.73Y', '10.73', '10.7', '10', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de pâtes alimentaires'),
  ('10.81Y', '10.81', '10.8', '10', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de sucre'),
  ('10.82Y', '10.82', '10.8', '10', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de cacao, de chocolat et de produits de confiserie'),
  ('10.83Y', '10.83', '10.8', '10', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Transformation du thé et du café'),
  ('10.84Y', '10.84', '10.8', '10', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de condiments et assaisonnements'),
  ('10.85Y', '10.85', '10.8', '10', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de plats préparés'),
  ('10.86Y', '10.86', '10.8', '10', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''aliments homogénéisés et diététiques'),
  ('10.89Y', '10.89', '10.8', '10', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''autres produits alimentaires n.c.a.'),
  ('10.91Y', '10.91', '10.9', '10', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''aliments pour animaux de ferme'),
  ('10.92Y', '10.92', '10.9', '10', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''aliments pour animaux de compagnie'),
  ('11.01Y', '11.01', '11.0', '11', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Production de boissons alcoolisées distillées'),
  ('11.02G', '11.02', '11.0', '11', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de vins effervescents'),
  ('11.02H', '11.02', '11.0', '11', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de vins non effervescents'),
  ('11.03Y', '11.03', '11.0', '11', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de cidre et autres boissons fermentées à base de fruits'),
  ('11.04Y', '11.04', '11.0', '11', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Production d''autres boissons fermentées non distillées'),
  ('11.05Y', '11.05', '11.0', '11', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de bière'),
  ('11.06Y', '11.06', '11.0', '11', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de malt'),
  ('11.07G', '11.07', '11.0', '11', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Industrie des eaux de table'),
  ('11.07H', '11.07', '11.0', '11', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Production d''autres boissons non alcoolisées'),
  ('12.00Y', '12.00', '12.0', '12', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de produits à base de tabac'),
  ('13.10Y', '13.10', '13.1', '13', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Préparation de fibres textiles et filature'),
  ('13.20Y', '13.20', '13.2', '13', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Tissage'),
  ('13.30Y', '13.30', '13.3', '13', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Ennoblissement textile'),
  ('13.91Y', '13.91', '13.9', '13', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''étoffes à mailles'),
  ('13.92Y', '13.92', '13.9', '13', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de textiles ménagers et d''articles d''ameublement confectionnés'),
  ('13.93Y', '13.93', '13.9', '13', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de tapis et moquettes'),
  ('13.94Y', '13.94', '13.9', '13', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de ficelles, cordes et filets'),
  ('13.95Y', '13.95', '13.9', '13', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de textiles non-tissés et articles non-tissés'),
  ('13.96Y', '13.96', '13.9', '13', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''autres textiles techniques et industriels'),
  ('13.99Y', '13.99', '13.9', '13', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''autres textiles n.c.a.'),
  ('14.10Y', '14.10', '14.1', '14', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''articles à mailles'),
  ('14.21Y', '14.21', '14.2', '14', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de vêtements de dessus'),
  ('14.22Y', '14.22', '14.2', '14', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de vêtements de dessous'),
  ('14.23Y', '14.23', '14.2', '14', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de vêtements de travail'),
  ('14.24Y', '14.24', '14.2', '14', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de vêtements en cuir et en fourrure'),
  ('14.29Y', '14.29', '14.2', '14', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''autres articles d''habillement et accessoires n.c.a.'),
  ('15.11Y', '15.11', '15.1', '15', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Tannage, apprêt et teinture des cuirs et des fourrures'),
  ('15.12Y', '15.12', '15.1', '15', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de bagages, de maroquinerie, sellerie et bourrellerie, en toutes matières'),
  ('15.20Y', '15.20', '15.2', '15', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de chaussures'),
  ('16.11Y', '16.11', '16.1', '16', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Sciage et rabotage du bois'),
  ('16.12Y', '16.12', '16.1', '16', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Façonnage et finition du bois'),
  ('16.21Y', '16.21', '16.2', '16', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de placage et de panneaux de bois'),
  ('16.22Y', '16.22', '16.2', '16', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de parquets assemblés'),
  ('16.23Y', '16.23', '16.2', '16', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de charpentes et d''autres menuiseries'),
  ('16.24Y', '16.24', '16.2', '16', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''emballages en bois'),
  ('16.25Y', '16.25', '16.2', '16', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de portes et fenêtres en bois'),
  ('16.26Y', '16.26', '16.2', '16', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de combustibles solides à partir de biomasse végétale'),
  ('16.27Y', '16.27', '16.2', '16', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Finition de produits en bois'),
  ('16.28Y', '16.28', '16.2', '16', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''objets divers en bois, d''objets en liège, vannerie et sparterie'),
  ('17.11Y', '17.11', '17.1', '17', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de pâte à papier'),
  ('17.12Y', '17.12', '17.1', '17', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de papier et de carton'),
  ('17.21Y', '17.21', '17.2', '17', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de papier et carton ondulés et d''emballages en papier ou en carton'),
  ('17.22Y', '17.22', '17.2', '17', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''articles en papier à usage sanitaire ou domestique'),
  ('17.23Y', '17.23', '17.2', '17', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''articles de papeterie'),
  ('17.24Y', '17.24', '17.2', '17', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de papiers peints'),
  ('17.25Y', '17.25', '17.2', '17', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''autres articles en papier ou en carton'),
  ('18.11Y', '18.11', '18.1', '18', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Imprimerie de journaux'),
  ('18.12Y', '18.12', '18.1', '18', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Autres activités d''imprimerie'),
  ('18.13Y', '18.13', '18.1', '18', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Activités de pré-presse'),
  ('18.14Y', '18.14', '18.1', '18', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Reliure et activités connexes'),
  ('18.20Y', '18.20', '18.2', '18', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Reproduction d''enregistrements'),
  ('19.10Y', '19.10', '19.1', '19', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Cokéfaction'),
  ('19.20Y', '19.20', '19.2', '19', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Raffinage du pétrole et fabrication de produits à base de combustibles fossiles'),
  ('20.11Y', '20.11', '20.1', '20', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de gaz industriels'),
  ('20.12Y', '20.12', '20.1', '20', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de colorants et de pigments'),
  ('20.13Y', '20.13', '20.1', '20', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''autres produits chimiques inorganiques de base'),
  ('20.14Y', '20.14', '20.1', '20', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''autres produits chimiques organiques de base'),
  ('20.15Y', '20.15', '20.1', '20', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de produits azotés et d''engrais'),
  ('20.16Y', '20.16', '20.1', '20', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de matières plastiques de base'),
  ('20.17Y', '20.17', '20.1', '20', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de caoutchouc synthétique'),
  ('20.20Y', '20.20', '20.2', '20', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de pesticides, de désinfectants et d''autres produits agrochimiques'),
  ('20.30Y', '20.30', '20.3', '20', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de peintures, vernis, encres et mastics'),
  ('20.41Y', '20.41', '20.4', '20', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de savons, détergents et produits d''entretien'),
  ('20.42Y', '20.42', '20.4', '20', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de parfums et de produits pour la toilette'),
  ('20.51Y', '20.51', '20.5', '20', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de biocarburants liquides'),
  ('20.59Y', '20.59', '20.5', '20', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''autres produits chimiques n.c.a.'),
  ('20.60Y', '20.60', '20.6', '20', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de fibres artificielles ou synthétiques'),
  ('21.10Y', '21.10', '21.1', '21', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de produits pharmaceutiques de base'),
  ('21.20Y', '21.20', '21.2', '21', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de préparations pharmaceutiques'),
  ('22.11Y', '22.11', '22.1', '22', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication et rechapage de pneus en caoutchouc et fabrication de chambres à air'),
  ('22.12Y', '22.12', '22.1', '22', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''autres articles en caoutchouc'),
  ('22.21Y', '22.21', '22.2', '22', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de plaques, feuilles, tubes et profilés en matières plastiques'),
  ('22.22Y', '22.22', '22.2', '22', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''emballages en matières plastiques'),
  ('22.23Y', '22.23', '22.2', '22', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de portes et fenêtres en matières plastiques'),
  ('22.24Y', '22.24', '22.2', '22', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''éléments en matières plastiques pour la construction'),
  ('22.25Y', '22.25', '22.2', '22', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Façonnage et finition de produits en matières plastiques'),
  ('22.26Y', '22.26', '22.2', '22', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''autres articles en matières plastiques'),
  ('23.11Y', '23.11', '23.1', '23', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de verre plat'),
  ('23.12Y', '23.12', '23.1', '23', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Façonnage et transformation du verre plat'),
  ('23.13Y', '23.13', '23.1', '23', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de verre creux'),
  ('23.14Y', '23.14', '23.1', '23', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de fibres de verre'),
  ('23.15Y', '23.15', '23.1', '23', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication et façonnage d''autres articles en verre, y compris verre technique'),
  ('23.20Y', '23.20', '23.2', '23', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de produits réfractaires'),
  ('23.31Y', '23.31', '23.3', '23', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de carreaux en céramique'),
  ('23.32Y', '23.32', '23.3', '23', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de briques, tuiles et produits de construction, en terre cuite'),
  ('23.41Y', '23.41', '23.4', '23', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''articles céramiques à usage domestique ou ornemental'),
  ('23.42Y', '23.42', '23.4', '23', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''appareils sanitaires en céramique'),
  ('23.43Y', '23.43', '23.4', '23', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''isolateurs et pièces isolantes en céramique'),
  ('23.44Y', '23.44', '23.4', '23', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''autres produits céramiques à usage technique'),
  ('23.45Y', '23.45', '23.4', '23', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''autres produits céramiques'),
  ('23.51Y', '23.51', '23.5', '23', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de ciment'),
  ('23.52Y', '23.52', '23.5', '23', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de chaux et plâtre'),
  ('23.61Y', '23.61', '23.6', '23', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''éléments en béton pour la construction'),
  ('23.62Y', '23.62', '23.6', '23', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''éléments en plâtre pour la construction'),
  ('23.63Y', '23.63', '23.6', '23', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de béton prêt à l''emploi'),
  ('23.64Y', '23.64', '23.6', '23', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de mortiers et de bétons secs'),
  ('23.65Y', '23.65', '23.6', '23', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''ouvrages en fibre-ciment'),
  ('23.66Y', '23.66', '23.6', '23', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''autres ouvrages en béton, en ciment ou en plâtre'),
  ('23.70Y', '23.70', '23.7', '23', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Taille, façonnage et finissage de pierres'),
  ('23.91Y', '23.91', '23.9', '23', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de produits abrasifs'),
  ('23.99Y', '23.99', '23.9', '23', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''autres produits minéraux non métalliques n.c.a.'),
  ('24.10Y', '24.10', '24.1', '24', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Sidérurgie'),
  ('24.20Y', '24.20', '24.2', '24', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de tubes, tuyaux, profilés creux et accessoires correspondants en acier'),
  ('24.31Y', '24.31', '24.3', '24', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Étirage à froid de barres'),
  ('24.32Y', '24.32', '24.3', '24', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Laminage à froid de feuillards'),
  ('24.33Y', '24.33', '24.3', '24', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Profilage à froid par formage ou pliage'),
  ('24.34Y', '24.34', '24.3', '24', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Tréfilage à froid'),
  ('24.41Y', '24.41', '24.4', '24', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Production de métaux précieux'),
  ('24.42Y', '24.42', '24.4', '24', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Métallurgie de l''aluminium'),
  ('24.43Y', '24.43', '24.4', '24', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Métallurgie du plomb, du zinc ou de l''étain'),
  ('24.44Y', '24.44', '24.4', '24', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Métallurgie du cuivre'),
  ('24.45Y', '24.45', '24.4', '24', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Métallurgie des autres métaux non ferreux'),
  ('24.46Y', '24.46', '24.4', '24', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Élaboration et transformation de matières nucléaires'),
  ('24.51Y', '24.51', '24.5', '24', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fonderie de fonte'),
  ('24.52Y', '24.52', '24.5', '24', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fonderie d''acier'),
  ('24.53Y', '24.53', '24.5', '24', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fonderie de métaux légers'),
  ('24.54Y', '24.54', '24.5', '24', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fonderie d''autres métaux non ferreux'),
  ('25.11Y', '25.11', '25.1', '25', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de structures métalliques et de parties de structures'),
  ('25.12Y', '25.12', '25.1', '25', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de portes et fenêtres en métal'),
  ('25.21Y', '25.21', '25.2', '25', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de radiateurs et de chaudières pour le chauffage central'),
  ('25.22Y', '25.22', '25.2', '25', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''autres réservoirs, citernes et conteneurs métalliques'),
  ('25.30Y', '25.30', '25.3', '25', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''armes et de munitions'),
  ('25.40Y', '25.40', '25.4', '25', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Forgeage et façonnage de métal ; métallurgie des poudres'),
  ('25.51Y', '25.51', '25.5', '25', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Revêtement des métaux'),
  ('25.52Y', '25.52', '25.5', '25', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Traitement thermique des métaux'),
  ('25.53Y', '25.53', '25.5', '25', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Usinage des métaux'),
  ('25.61Y', '25.61', '25.6', '25', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de coutellerie'),
  ('25.62Y', '25.62', '25.6', '25', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de serrures et de ferrures'),
  ('25.63Y', '25.63', '25.6', '25', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''outillage'),
  ('25.91Y', '25.91', '25.9', '25', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de fûts et emballages métalliques similaires'),
  ('25.92Y', '25.92', '25.9', '25', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''emballages métalliques légers'),
  ('25.93Y', '25.93', '25.9', '25', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''articles en fils métalliques, de chaînes et de ressorts'),
  ('25.94Y', '25.94', '25.9', '25', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de vis et de boulons'),
  ('25.99Y', '25.99', '25.9', '25', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''autres produits métalliques n.c.a.'),
  ('26.11Y', '26.11', '26.1', '26', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de composants électroniques'),
  ('26.12Y', '26.12', '26.1', '26', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de cartes électroniques assemblées'),
  ('26.20Y', '26.20', '26.2', '26', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''ordinateurs et d''équipements périphériques'),
  ('26.30Y', '26.30', '26.3', '26', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''équipements de communication'),
  ('26.40Y', '26.40', '26.4', '26', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de produits électroniques grand public'),
  ('26.51Y', '26.51', '26.5', '26', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''instruments et d''appareils de mesure, d''essai et de navigation'),
  ('26.52Y', '26.52', '26.5', '26', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Horlogerie'),
  ('26.60Y', '26.60', '26.6', '26', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''équipements d''irradiation médicale, d''équipements électromédicaux et électrothérapeutiques'),
  ('26.70Y', '26.70', '26.7', '26', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de matériels optique et photographique et de supports magnétiques et optiques'),
  ('27.11Y', '27.11', '27.1', '27', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de moteurs, génératrices et transformateurs électriques'),
  ('27.12Y', '27.12', '27.1', '27', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de matériel de distribution et de commande électrique'),
  ('27.20Y', '27.20', '27.2', '27', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de piles et d''accumulateurs électriques'),
  ('27.31Y', '27.31', '27.3', '27', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de câbles de fibres optiques'),
  ('27.32Y', '27.32', '27.3', '27', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''autres fils et câbles électroniques ou électriques'),
  ('27.33Y', '27.33', '27.3', '27', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de matériel d''installation électrique'),
  ('27.40Y', '27.40', '27.4', '27', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''appareils d''éclairage'),
  ('27.51Y', '27.51', '27.5', '27', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''appareils électroménagers'),
  ('27.52Y', '27.52', '27.5', '27', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''appareils ménagers non électriques'),
  ('27.90Y', '27.90', '27.9', '27', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''autres matériels électriques'),
  ('28.11Y', '28.11', '28.1', '28', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de moteurs et turbines, à l''exception des moteurs d''avions et de véhicules'),
  ('28.12Y', '28.12', '28.1', '28', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''équipements de transmission de puissance hydrauliques et pneumatiques'),
  ('28.13G', '28.13', '28.1', '28', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''autres pompes'),
  ('28.13H', '28.13', '28.1', '28', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''autres compresseurs'),
  ('28.14Y', '28.14', '28.1', '28', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''autres articles de robinetterie'),
  ('28.15Y', '28.15', '28.1', '28', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de roulements et de transmissions mécaniques'),
  ('28.21Y', '28.21', '28.2', '28', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de fours et brûleurs et d''équipements fixes de chauffage domestique'),
  ('28.22Y', '28.22', '28.2', '28', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de matériel de levage et de manutention'),
  ('28.23Y', '28.23', '28.2', '28', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de machines et d''équipements de bureau (à l''exception des ordinateurs et équipements périphériques)'),
  ('28.24Y', '28.24', '28.2', '28', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''outillage portatif à moteur incorporé'),
  ('28.25Y', '28.25', '28.2', '28', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''équipements aérauliques et frigorifiques industriels'),
  ('28.29Y', '28.29', '28.2', '28', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de machines diverses d''usage général'),
  ('28.30Y', '28.30', '28.3', '28', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de machines agricoles et forestières'),
  ('28.41Y', '28.41', '28.4', '28', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de machines-outils pour le formage et le travail des métaux'),
  ('28.42Y', '28.42', '28.4', '28', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''autres machines-outils'),
  ('28.91Y', '28.91', '28.9', '28', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de machines pour la métallurgie'),
  ('28.92Y', '28.92', '28.9', '28', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de machines pour l''extraction ou la construction'),
  ('28.93Y', '28.93', '28.9', '28', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de machines pour l''industrie agro-alimentaire'),
  ('28.94Y', '28.94', '28.9', '28', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de machines pour les industries textiles et du cuir'),
  ('28.95Y', '28.95', '28.9', '28', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de machines pour les industries du papier et du carton'),
  ('28.96Y', '28.96', '28.9', '28', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de machines pour le travail du caoutchouc ou des plastiques'),
  ('28.97Y', '28.97', '28.9', '28', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de machines de fabrication additive'),
  ('28.99Y', '28.99', '28.9', '28', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''autres machines d''usage spécifique n.c.a.'),
  ('29.10Y', '29.10', '29.1', '29', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Construction de véhicules automobiles'),
  ('29.20Y', '29.20', '29.2', '29', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de carrosseries de véhicules automobiles ; fabrication de remorques et de semi-remorques'),
  ('29.31Y', '29.31', '29.3', '29', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''équipements électriques et électroniques automobiles'),
  ('29.32Y', '29.32', '29.3', '29', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''autres équipements automobiles'),
  ('30.11Y', '30.11', '30.1', '30', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Construction de navires et de structures flottantes civiles'),
  ('30.12Y', '30.12', '30.1', '30', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Construction de bateaux de plaisance'),
  ('30.13Y', '30.13', '30.1', '30', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Construction de bateaux et navires militaires'),
  ('30.20Y', '30.20', '30.2', '30', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Construction de locomotives et d''autre matériel ferroviaire roulant'),
  ('30.31Y', '30.31', '30.3', '30', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Construction aéronautique et spatiale civile'),
  ('30.32Y', '30.32', '30.3', '30', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Construction aéronautique et spatiale militaire'),
  ('30.40Y', '30.40', '30.4', '30', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Construction de véhicules militaires de combat'),
  ('30.91Y', '30.91', '30.9', '30', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de motocycles'),
  ('30.92Y', '30.92', '30.9', '30', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de bicyclettes et de véhicules pour invalides'),
  ('30.99Y', '30.99', '30.9', '30', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''autres équipements de transport n.c.a.'),
  ('31.00G', '31.00', '31.0', '31', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de meubles à destination de professionnels'),
  ('31.00H', '31.00', '31.0', '31', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de meubles de cuisine et salle de bain'),
  ('31.00J', '31.00', '31.0', '31', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''autres meubles domestiques, de sommiers et de matelas'),
  ('32.11Y', '32.11', '32.1', '32', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Frappe de monnaie'),
  ('32.12Y', '32.12', '32.1', '32', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''articles de joaillerie et bijouterie'),
  ('32.13Y', '32.13', '32.1', '32', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''articles de bijouterie fantaisie et articles similaires'),
  ('32.20Y', '32.20', '32.2', '32', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''instruments de musique'),
  ('32.30Y', '32.30', '32.3', '32', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''articles de sport'),
  ('32.40Y', '32.40', '32.4', '32', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication de jeux et jouets'),
  ('32.50Y', '32.50', '32.5', '32', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''instruments et de fournitures à usage médical et dentaire'),
  ('32.91Y', '32.91', '32.9', '32', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Fabrication d''articles de brosserie'),
  ('32.99Y', '32.99', '32.9', '32', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Autres activités manufacturières n.c.a.'),
  ('33.11Y', '33.11', '33.1', '33', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Réparation et entretien d''ouvrages en métaux'),
  ('33.12Y', '33.12', '33.1', '33', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Réparation et entretien de machines'),
  ('33.13Y', '33.13', '33.1', '33', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Réparation et entretien de matériels électroniques et optiques'),
  ('33.14Y', '33.14', '33.1', '33', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Réparation et entretien d''équipements électriques'),
  ('33.15Y', '33.15', '33.1', '33', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Réparation et entretien de bateaux et navires civils'),
  ('33.16Y', '33.16', '33.1', '33', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Réparation et entretien d''aéronefs et d''engins spatiaux civils'),
  ('33.17Y', '33.17', '33.1', '33', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Réparation et entretien d''autres équipements de transport civils'),
  ('33.18G', '33.18', '33.1', '33', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Réparation et entretien d''aéronefs et d''engins spatiaux militaires'),
  ('33.18H', '33.18', '33.1', '33', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Réparation et entretien de véhicules de combat, de navires et de bateaux militaires'),
  ('33.19Y', '33.19', '33.1', '33', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Réparation et entretien d''autres équipements'),
  ('33.20Y', '33.20', '33.2', '33', 'C', 'INDUSTRIE MANUFACTURIÈRE', 'Installation de machines et d''équipements industriels'),
  ('35.11Y', '35.11', '35.1', '35', 'D', 'PRODUCTION ET DISTRIBUTION D''ÉLECTRICITÉ, DE GAZ, DE VAPEUR ET D''AIR CONDITIONNÉ', 'Production d''électricité à partir de sources non renouvelables'),
  ('35.12Y', '35.12', '35.1', '35', 'D', 'PRODUCTION ET DISTRIBUTION D''ÉLECTRICITÉ, DE GAZ, DE VAPEUR ET D''AIR CONDITIONNÉ', 'Production d''électricité à partir de sources renouvelables'),
  ('35.13Y', '35.13', '35.1', '35', 'D', 'PRODUCTION ET DISTRIBUTION D''ÉLECTRICITÉ, DE GAZ, DE VAPEUR ET D''AIR CONDITIONNÉ', 'Transport d''électricité'),
  ('35.14Y', '35.14', '35.1', '35', 'D', 'PRODUCTION ET DISTRIBUTION D''ÉLECTRICITÉ, DE GAZ, DE VAPEUR ET D''AIR CONDITIONNÉ', 'Distribution d''électricité'),
  ('35.15G', '35.15', '35.1', '35', 'D', 'PRODUCTION ET DISTRIBUTION D''ÉLECTRICITÉ, DE GAZ, DE VAPEUR ET D''AIR CONDITIONNÉ', 'Exploitation d''installations de recharge pour véhicules électriques'),
  ('35.15H', '35.15', '35.1', '35', 'D', 'PRODUCTION ET DISTRIBUTION D''ÉLECTRICITÉ, DE GAZ, DE VAPEUR ET D''AIR CONDITIONNÉ', 'Autre commerce d''électricité'),
  ('35.16Y', '35.16', '35.1', '35', 'D', 'PRODUCTION ET DISTRIBUTION D''ÉLECTRICITÉ, DE GAZ, DE VAPEUR ET D''AIR CONDITIONNÉ', 'Stockage de l''électricité'),
  ('35.21Y', '35.21', '35.2', '35', 'D', 'PRODUCTION ET DISTRIBUTION D''ÉLECTRICITÉ, DE GAZ, DE VAPEUR ET D''AIR CONDITIONNÉ', 'Production de gaz'),
  ('35.22Y', '35.22', '35.2', '35', 'D', 'PRODUCTION ET DISTRIBUTION D''ÉLECTRICITÉ, DE GAZ, DE VAPEUR ET D''AIR CONDITIONNÉ', 'Distribution de combustibles gazeux par conduites'),
  ('35.23Y', '35.23', '35.2', '35', 'D', 'PRODUCTION ET DISTRIBUTION D''ÉLECTRICITÉ, DE GAZ, DE VAPEUR ET D''AIR CONDITIONNÉ', 'Commerce de combustibles gazeux par conduites'),
  ('35.24Y', '35.24', '35.2', '35', 'D', 'PRODUCTION ET DISTRIBUTION D''ÉLECTRICITÉ, DE GAZ, DE VAPEUR ET D''AIR CONDITIONNÉ', 'Stockage de gaz dans le cadre de services d''approvisionnement en réseau'),
  ('35.30Y', '35.30', '35.3', '35', 'D', 'PRODUCTION ET DISTRIBUTION D''ÉLECTRICITÉ, DE GAZ, DE VAPEUR ET D''AIR CONDITIONNÉ', 'Production et distribution de vapeur et d''air conditionné'),
  ('35.40Y', '35.40', '35.4', '35', 'D', 'PRODUCTION ET DISTRIBUTION D''ÉLECTRICITÉ, DE GAZ, DE VAPEUR ET D''AIR CONDITIONNÉ', 'Activités des courtiers et agents pour l''électricité et le gaz naturel'),
  ('36.00Y', '36.00', '36.0', '36', 'E', 'PRODUCTION ET DISTRIBUTION D''EAU ; ASSAINISSEMENT, GESTION DES DÉCHETS ET DÉPOLLUTION', 'Captage, traitement et distribution d''eau'),
  ('37.00Y', '37.00', '37.0', '37', 'E', 'PRODUCTION ET DISTRIBUTION D''EAU ; ASSAINISSEMENT, GESTION DES DÉCHETS ET DÉPOLLUTION', 'Collecte et traitement des eaux usées'),
  ('38.11Y', '38.11', '38.1', '38', 'E', 'PRODUCTION ET DISTRIBUTION D''EAU ; ASSAINISSEMENT, GESTION DES DÉCHETS ET DÉPOLLUTION', 'Collecte des déchets non dangereux'),
  ('38.12Y', '38.12', '38.1', '38', 'E', 'PRODUCTION ET DISTRIBUTION D''EAU ; ASSAINISSEMENT, GESTION DES DÉCHETS ET DÉPOLLUTION', 'Collecte des déchets dangereux'),
  ('38.21Y', '38.21', '38.2', '38', 'E', 'PRODUCTION ET DISTRIBUTION D''EAU ; ASSAINISSEMENT, GESTION DES DÉCHETS ET DÉPOLLUTION', 'Récupération de matériaux'),
  ('38.22Y', '38.22', '38.2', '38', 'E', 'PRODUCTION ET DISTRIBUTION D''EAU ; ASSAINISSEMENT, GESTION DES DÉCHETS ET DÉPOLLUTION', 'Valorisation énergétique'),
  ('38.23Y', '38.23', '38.2', '38', 'E', 'PRODUCTION ET DISTRIBUTION D''EAU ; ASSAINISSEMENT, GESTION DES DÉCHETS ET DÉPOLLUTION', 'Autre valorisation des déchets'),
  ('38.31Y', '38.31', '38.3', '38', 'E', 'PRODUCTION ET DISTRIBUTION D''EAU ; ASSAINISSEMENT, GESTION DES DÉCHETS ET DÉPOLLUTION', 'Incinération sans récupération d''énergie'),
  ('38.32Y', '38.32', '38.3', '38', 'E', 'PRODUCTION ET DISTRIBUTION D''EAU ; ASSAINISSEMENT, GESTION DES DÉCHETS ET DÉPOLLUTION', 'Mise en décharge ou stockage permanent'),
  ('38.33Y', '38.33', '38.3', '38', 'E', 'PRODUCTION ET DISTRIBUTION D''EAU ; ASSAINISSEMENT, GESTION DES DÉCHETS ET DÉPOLLUTION', 'Autre élimination des déchets'),
  ('39.00Y', '39.00', '39.0', '39', 'E', 'PRODUCTION ET DISTRIBUTION D''EAU ; ASSAINISSEMENT, GESTION DES DÉCHETS ET DÉPOLLUTION', 'Activités de dépollution et autres activités de service de gestion des déchets'),
  ('41.00G', '41.00', '41.0', '41', 'F', 'CONSTRUCTION', 'Construction de maisons individuelles'),
  ('41.00H', '41.00', '41.0', '41', 'F', 'CONSTRUCTION', 'Construction d''autres bâtiments'),
  ('42.11Y', '42.11', '42.1', '42', 'F', 'CONSTRUCTION', 'Construction de routes et autoroutes'),
  ('42.12Y', '42.12', '42.1', '42', 'F', 'CONSTRUCTION', 'Construction de voies ferrées de surface et souterraines'),
  ('42.13G', '42.13', '42.1', '42', 'F', 'CONSTRUCTION', 'Construction de ponts et de viaducs'),
  ('42.13H', '42.13', '42.1', '42', 'F', 'CONSTRUCTION', 'Construction de tunnels'),
  ('42.21Y', '42.21', '42.2', '42', 'F', 'CONSTRUCTION', 'Construction de réseaux pour fluides'),
  ('42.22Y', '42.22', '42.2', '42', 'F', 'CONSTRUCTION', 'Construction de réseaux électriques et de télécommunications'),
  ('42.91Y', '42.91', '42.9', '42', 'F', 'CONSTRUCTION', 'Construction d''ouvrages maritimes et fluviaux'),
  ('42.99Y', '42.99', '42.9', '42', 'F', 'CONSTRUCTION', 'Construction d''autres ouvrages de génie civil n.c.a.'),
  ('43.11Y', '43.11', '43.1', '43', 'F', 'CONSTRUCTION', 'Démolition'),
  ('43.12G', '43.12', '43.1', '43', 'F', 'CONSTRUCTION', 'Travaux de terrassement courants et travaux préparatoires'),
  ('43.12H', '43.12', '43.1', '43', 'F', 'CONSTRUCTION', 'Travaux de terrassement spécialisés ou de grande masse'),
  ('43.13Y', '43.13', '43.1', '43', 'F', 'CONSTRUCTION', 'Forages et sondages'),
  ('43.21G', '43.21', '43.2', '43', 'F', 'CONSTRUCTION', 'Travaux d''installation électrique dans tous locaux'),
  ('43.21H', '43.21', '43.2', '43', 'F', 'CONSTRUCTION', 'Travaux d''installation électrique sur la voie'),
  ('43.22G', '43.22', '43.2', '43', 'F', 'CONSTRUCTION', 'Travaux d''installation d''eau et de gaz en tous locaux'),
  ('43.22H', '43.22', '43.2', '43', 'F', 'CONSTRUCTION', 'Travaux d''installation d''équipements thermiques et de climatisation'),
  ('43.23Y', '43.23', '43.2', '43', 'F', 'CONSTRUCTION', 'Mise en place de l''isolation'),
  ('43.24Y', '43.24', '43.2', '43', 'F', 'CONSTRUCTION', 'Autres travaux d''installation'),
  ('43.31Y', '43.31', '43.3', '43', 'F', 'CONSTRUCTION', 'Travaux de plâtrerie'),
  ('43.32G', '43.32', '43.3', '43', 'F', 'CONSTRUCTION', 'Travaux de menuiserie bois et PVC'),
  ('43.32H', '43.32', '43.3', '43', 'F', 'CONSTRUCTION', 'Travaux de menuiserie métallique'),
  ('43.33Y', '43.33', '43.3', '43', 'F', 'CONSTRUCTION', 'Travaux de revêtement des sols et des murs'),
  ('43.34G', '43.34', '43.3', '43', 'F', 'CONSTRUCTION', 'Travaux de peinture'),
  ('43.34H', '43.34', '43.3', '43', 'F', 'CONSTRUCTION', 'Travaux de vitrerie'),
  ('43.35Y', '43.35', '43.3', '43', 'F', 'CONSTRUCTION', 'Autres travaux de finition'),
  ('43.41G', '43.41', '43.4', '43', 'F', 'CONSTRUCTION', 'Travaux de charpente'),
  ('43.41H', '43.41', '43.4', '43', 'F', 'CONSTRUCTION', 'Travaux de couverture par éléments'),
  ('43.41J', '43.41', '43.4', '43', 'F', 'CONSTRUCTION', 'Travaux d''étanchéification pour la toiture'),
  ('43.42G', '43.42', '43.4', '43', 'F', 'CONSTRUCTION', 'Travaux de montage d''éléments de construction préfabriqués pour bâtiments, en acier'),
  ('43.42H', '43.42', '43.4', '43', 'F', 'CONSTRUCTION', 'Travaux de montage d''éléments de construction préfabriqués pour bâtiments, en bois'),
  ('43.42J', '43.42', '43.4', '43', 'F', 'CONSTRUCTION', 'Autres travaux de construction spécialisés dans la construction de bâtiments n.c.a.'),
  ('43.50Y', '43.50', '43.5', '43', 'F', 'CONSTRUCTION', 'Travaux de construction spécialisés en génie civil'),
  ('43.60Y', '43.60', '43.6', '43', 'F', 'CONSTRUCTION', 'Activités de service d''intermédiation pour des travaux de construction spécialisés'),
  ('43.91Y', '43.91', '43.9', '43', 'F', 'CONSTRUCTION', 'Travaux de maçonnerie et de pose de briques'),
  ('43.99G', '43.99', '43.9', '43', 'F', 'CONSTRUCTION', 'Location avec opérateur d''équipement de construction'),
  ('43.99H', '43.99', '43.9', '43', 'F', 'CONSTRUCTION', 'Tous les autres travaux de construction spécialisés n.c.a.'),
  ('46.11Y', '46.11', '46.1', '46', 'G', 'COMMERCE', 'Activités d''intermédiaire du commerce de gros en matières premières agricoles, animaux vivants, matières premières textiles et produits semi-finis'),
  ('46.12Y', '46.12', '46.1', '46', 'G', 'COMMERCE', 'Activités d''intermédiaire du commerce de gros en combustibles, minerais, métaux et produits chimiques'),
  ('46.13Y', '46.13', '46.1', '46', 'G', 'COMMERCE', 'Activités d''intermédiaire du commerce de gros en bois et matériaux de construction'),
  ('46.14Y', '46.14', '46.1', '46', 'G', 'COMMERCE', 'Activités d''intermédiaire du commerce de gros en machines, équipements industriels, navires et avions'),
  ('46.15Y', '46.15', '46.1', '46', 'G', 'COMMERCE', 'Activités d''intermédiaire du commerce de gros en meubles, biens domestiques et quincaillerie'),
  ('46.16Y', '46.16', '46.1', '46', 'G', 'COMMERCE', 'Activités d''intermédiaire du commerce de gros en textiles, habillement, fourrures, chaussures et articles en cuir'),
  ('46.17G', '46.17', '46.1', '46', 'G', 'COMMERCE', 'Activités d''intermédiation des centrales d''achat alimentaires'),
  ('46.17H', '46.17', '46.1', '46', 'G', 'COMMERCE', 'Autres activités d''intermédiaire du commerce de gros en denrées, boissons et tabac'),
  ('46.18Y', '46.18', '46.1', '46', 'G', 'COMMERCE', 'Activités d''intermédiaire spécialisé dans le commerce de gros d''autres produits spécifiques'),
  ('46.19G', '46.19', '46.1', '46', 'G', 'COMMERCE', 'Activités d''intermédiation des centrales d''achat non spécialisées'),
  ('46.19H', '46.19', '46.1', '46', 'G', 'COMMERCE', 'Autres activités d''intermédiaire non spécialisé du commerce de gros'),
  ('46.21Y', '46.21', '46.2', '46', 'G', 'COMMERCE', 'Commerce de gros de céréales, de tabac non manufacturé, de semences et d''aliments pour animaux'),
  ('46.22Y', '46.22', '46.2', '46', 'G', 'COMMERCE', 'Commerce de gros de fleurs et de plantes'),
  ('46.23Y', '46.23', '46.2', '46', 'G', 'COMMERCE', 'Commerce de gros d''animaux vivants'),
  ('46.24Y', '46.24', '46.2', '46', 'G', 'COMMERCE', 'Commerce de gros de cuirs et de peaux'),
  ('46.31Y', '46.31', '46.3', '46', 'G', 'COMMERCE', 'Commerce de gros de fruits et légumes'),
  ('46.32G', '46.32', '46.3', '46', 'G', 'COMMERCE', 'Commerce de gros de viandes et de produits à base de viande'),
  ('46.32H', '46.32', '46.3', '46', 'G', 'COMMERCE', 'Commerce de gros de poissons, crustacés et mollusques et de produits à base de poisson'),
  ('46.33Y', '46.33', '46.3', '46', 'G', 'COMMERCE', 'Commerce de gros de produits laitiers, œufs, huiles et matières grasses comestibles'),
  ('46.34Y', '46.34', '46.3', '46', 'G', 'COMMERCE', 'Commerce de gros de boissons'),
  ('46.35Y', '46.35', '46.3', '46', 'G', 'COMMERCE', 'Commerce de gros de produits à base de tabac'),
  ('46.36Y', '46.36', '46.3', '46', 'G', 'COMMERCE', 'Commerce de gros de sucre, chocolat et confiserie'),
  ('46.37Y', '46.37', '46.3', '46', 'G', 'COMMERCE', 'Commerce de gros de café, thé, cacao et épices'),
  ('46.38Y', '46.38', '46.3', '46', 'G', 'COMMERCE', 'Commerce de gros d''autres denrées alimentaires'),
  ('46.39Y', '46.39', '46.3', '46', 'G', 'COMMERCE', 'Commerce de gros non spécialisé de denrées, boissons et tabac'),
  ('46.41Y', '46.41', '46.4', '46', 'G', 'COMMERCE', 'Commerce de gros de textiles'),
  ('46.42Y', '46.42', '46.4', '46', 'G', 'COMMERCE', 'Commerce de gros d''habillement et de chaussures'),
  ('46.43G', '46.43', '46.4', '46', 'G', 'COMMERCE', 'Commerce de gros d''appareils de génie climatique'),
  ('46.43H', '46.43', '46.4', '46', 'G', 'COMMERCE', 'Commerce de gros d''autres appareils électroménagers'),
  ('46.44Y', '46.44', '46.4', '46', 'G', 'COMMERCE', 'Commerce de gros de vaisselle, verrerie et produits d''entretien'),
  ('46.45Y', '46.45', '46.4', '46', 'G', 'COMMERCE', 'Commerce de gros de parfumerie et de produits de beauté'),
  ('46.46Y', '46.46', '46.4', '46', 'G', 'COMMERCE', 'Commerce de gros de produits pharmaceutiques et médicaux'),
  ('46.47Y', '46.47', '46.4', '46', 'G', 'COMMERCE', 'Commerce de gros de meubles à usage domestique, de bureau et de magasin, de tapis et d''appareils d''éclairage'),
  ('46.48Y', '46.48', '46.4', '46', 'G', 'COMMERCE', 'Commerce de gros d''articles d''horlogerie et de bijouterie'),
  ('46.49Y', '46.49', '46.4', '46', 'G', 'COMMERCE', 'Commerce de gros d''autres biens domestiques'),
  ('46.50Y', '46.50', '46.5', '46', 'G', 'COMMERCE', 'Commerce de gros d''équipements de l''information et de la communication'),
  ('46.61Y', '46.61', '46.6', '46', 'G', 'COMMERCE', 'Commerce de gros de matériel agricole'),
  ('46.62Y', '46.62', '46.6', '46', 'G', 'COMMERCE', 'Commerce de gros de machines-outils'),
  ('46.63Y', '46.63', '46.6', '46', 'G', 'COMMERCE', 'Commerce de gros de machines pour l''extraction, la construction et le génie civil'),
  ('46.64G', '46.64', '46.6', '46', 'G', 'COMMERCE', 'Commerce de gros d''autre matériel électrique'),
  ('46.64H', '46.64', '46.6', '46', 'G', 'COMMERCE', 'Commerce de gros de matériels de manutention et de levage'),
  ('46.64J', '46.64', '46.6', '46', 'G', 'COMMERCE', 'Commerce de gros d''autres machines et équipements pour l''industrie et le transport'),
  ('46.64K', '46.64', '46.6', '46', 'G', 'COMMERCE', 'Commerce de gros d''autres machines et équipements pour le commerce et les services'),
  ('46.71G', '46.71', '46.7', '46', 'G', 'COMMERCE', 'Commerce de gros de véhicules automobiles légers (moins de 3,5 tonnes)'),
  ('46.71H', '46.71', '46.7', '46', 'G', 'COMMERCE', 'Commerce de gros d''autres véhicules automobiles'),
  ('46.72Y', '46.72', '46.7', '46', 'G', 'COMMERCE', 'Commerce de gros de pièces et accessoires de véhicules automobiles'),
  ('46.73Y', '46.73', '46.7', '46', 'G', 'COMMERCE', 'Commerce de gros de motocycles et de pièces et accessoires pour motocycles'),
  ('46.81Y', '46.81', '46.8', '46', 'G', 'COMMERCE', 'Commerce de gros de combustibles solides, liquides et gazeux et de produits annexes'),
  ('46.82Y', '46.82', '46.8', '46', 'G', 'COMMERCE', 'Commerce de gros de minerais et de métaux'),
  ('46.83G', '46.83', '46.8', '46', 'G', 'COMMERCE', 'Commerce de gros de bois et matériaux de construction'),
  ('46.83H', '46.83', '46.8', '46', 'G', 'COMMERCE', 'Commerce de gros d''appareils sanitaires'),
  ('46.83J', '46.83', '46.8', '46', 'G', 'COMMERCE', 'Commerce de gros de matériaux de décoration'),
  ('46.84G', '46.84', '46.8', '46', 'G', 'COMMERCE', 'Commerce de gros de quincaillerie et de matériel de bricolage'),
  ('46.84H', '46.84', '46.8', '46', 'G', 'COMMERCE', 'Commerce de gros de fournitures pour plomberie et chauffage'),
  ('46.85Y', '46.85', '46.8', '46', 'G', 'COMMERCE', 'Commerce de gros de produits chimiques'),
  ('46.86Y', '46.86', '46.8', '46', 'G', 'COMMERCE', 'Commerce de gros d''autres produits intermédiaires'),
  ('46.87Y', '46.87', '46.8', '46', 'G', 'COMMERCE', 'Commerce de gros de déchets et débris'),
  ('46.89Y', '46.89', '46.8', '46', 'G', 'COMMERCE', 'Autre commerce de gros spécialisé n.c.a.'),
  ('46.90Y', '46.90', '46.9', '46', 'G', 'COMMERCE', 'Commerce de gros non spécialisé'),
  ('47.11G', '47.11', '47.1', '47', 'G', 'COMMERCE', 'Commerce de détail non spécialisé à prédominance alimentaire en magasin de moins de 120 m²'),
  ('47.11H', '47.11', '47.1', '47', 'G', 'COMMERCE', 'Commerce de détail non spécialisé à prédominance alimentaire en magasin de 120 à 400 m² (supérette)'),
  ('47.11J', '47.11', '47.1', '47', 'G', 'COMMERCE', 'Commerce de détail non spécialisé à prédominance alimentaire en magasin de 400 à 2500 m² (supermarché)'),
  ('47.11K', '47.11', '47.1', '47', 'G', 'COMMERCE', 'Commerce de détail non spécialisé à prédominance alimentaire en magasin de plus de 2500 m² (hypermarché)'),
  ('47.11L', '47.11', '47.1', '47', 'G', 'COMMERCE', 'Commerce de détail non spécialisé à prédominance alimentaire hors magasin'),
  ('47.12G', '47.12', '47.1', '47', 'G', 'COMMERCE', 'Autre commerce de détail non spécialisé en magasin de plus de 2500 m² (grand magasin)'),
  ('47.12H', '47.12', '47.1', '47', 'G', 'COMMERCE', 'Autre commerce de détail non spécialisé en magasin de moins de 2500 m² ou hors magasin'),
  ('47.21Y', '47.21', '47.2', '47', 'G', 'COMMERCE', 'Commerce de détail de fruits et légumes'),
  ('47.22Y', '47.22', '47.2', '47', 'G', 'COMMERCE', 'Commerce de détail de viande et de produits à base de viande'),
  ('47.23Y', '47.23', '47.2', '47', 'G', 'COMMERCE', 'Commerce de détail de poisson, de crustacés et de mollusques'),
  ('47.24Y', '47.24', '47.2', '47', 'G', 'COMMERCE', 'Commerce de détail de pain, de pâtisserie et de confiserie'),
  ('47.25Y', '47.25', '47.2', '47', 'G', 'COMMERCE', 'Commerce de détail de boissons'),
  ('47.26Y', '47.26', '47.2', '47', 'G', 'COMMERCE', 'Commerce de détail de produits à base de tabac'),
  ('47.27G', '47.27', '47.2', '47', 'G', 'COMMERCE', 'Commerce de détail de produits laitiers et d''œufs'),
  ('47.27H', '47.27', '47.2', '47', 'G', 'COMMERCE', 'Commerce de détail spécialisé d''autres produits d''épicerie et d''autres produits alimentaires n.c.a.'),
  ('47.30Y', '47.30', '47.3', '47', 'G', 'COMMERCE', 'Commerce de détail de carburants'),
  ('47.40Y', '47.40', '47.4', '47', 'G', 'COMMERCE', 'Commerce de détail d''équipements de l''information et de la communication'),
  ('47.51Y', '47.51', '47.5', '47', 'G', 'COMMERCE', 'Commerce de détail de textiles'),
  ('47.52G', '47.52', '47.5', '47', 'G', 'COMMERCE', 'Commerce de détail de quincaillerie, de matériaux de construction et de bricolage, de peinture et de verre en magasin de moins de 400 m²'),
  ('47.52H', '47.52', '47.5', '47', 'G', 'COMMERCE', 'Commerce de détail de quincaillerie, de matériaux de construction et de bricolage, de peinture et de verre en magasin de plus de 400 m² ou hors magasin'),
  ('47.53Y', '47.53', '47.5', '47', 'G', 'COMMERCE', 'Commerce de détail de tapis, moquettes et revêtements de murs et de sols'),
  ('47.54Y', '47.54', '47.5', '47', 'G', 'COMMERCE', 'Commerce de détail d''appareils électroménagers'),
  ('47.55G', '47.55', '47.5', '47', 'G', 'COMMERCE', 'Commerce de détail de meubles'),
  ('47.55H', '47.55', '47.5', '47', 'G', 'COMMERCE', 'Commerce de détail d''appareils d''éclairage, de vaisselle et d''autres équipements du foyer'),
  ('47.61Y', '47.61', '47.6', '47', 'G', 'COMMERCE', 'Commerce de détail de livres'),
  ('47.62Y', '47.62', '47.6', '47', 'G', 'COMMERCE', 'Commerce de détail de journaux et autres publications périodiques et de papeterie'),
  ('47.63Y', '47.63', '47.6', '47', 'G', 'COMMERCE', 'Commerce de détail d''articles de sport'),
  ('47.64Y', '47.64', '47.6', '47', 'G', 'COMMERCE', 'Commerce de détail de jeux et jouets'),
  ('47.69Y', '47.69', '47.6', '47', 'G', 'COMMERCE', 'Commerce de détail de biens culturels et de loisirs n.c.a.'),
  ('47.71Y', '47.71', '47.7', '47', 'G', 'COMMERCE', 'Commerce de détail d''habillement'),
  ('47.72G', '47.72', '47.7', '47', 'G', 'COMMERCE', 'Commerce de détail de chaussures'),
  ('47.72H', '47.72', '47.7', '47', 'G', 'COMMERCE', 'Commerce de détail de maroquinerie et d''articles de voyage'),
  ('47.73Y', '47.73', '47.7', '47', 'G', 'COMMERCE', 'Commerce de détail de produits pharmaceutiques'),
  ('47.74G', '47.74', '47.7', '47', 'G', 'COMMERCE', 'Commerce de détail d''optique'),
  ('47.74H', '47.74', '47.7', '47', 'G', 'COMMERCE', 'Commerce de détail d''autres articles médicaux et orthopédiques'),
  ('47.75Y', '47.75', '47.7', '47', 'G', 'COMMERCE', 'Commerce de détail de parfumerie et de produits de beauté'),
  ('47.76Y', '47.76', '47.7', '47', 'G', 'COMMERCE', 'Commerce de détail de fleurs, plantes, engrais, animaux de compagnie et aliments pour ces animaux'),
  ('47.77Y', '47.77', '47.7', '47', 'G', 'COMMERCE', 'Commerce de détail d''articles d''horlogerie et de bijouterie'),
  ('47.78G', '47.78', '47.7', '47', 'G', 'COMMERCE', 'Commerce de détail de charbons et combustibles'),
  ('47.78H', '47.78', '47.7', '47', 'G', 'COMMERCE', 'Commerce de détail spécialisé d''autres biens neufs n.c.a.'),
  ('47.79G', '47.79', '47.7', '47', 'G', 'COMMERCE', 'Commerce de détail d''antiquités et livres anciens'),
  ('47.79H', '47.79', '47.7', '47', 'G', 'COMMERCE', 'Commerce de détail d''autres biens d''occasion'),
  ('47.81Y', '47.81', '47.8', '47', 'G', 'COMMERCE', 'Commerce de détail de véhicules automobiles'),
  ('47.82Y', '47.82', '47.8', '47', 'G', 'COMMERCE', 'Commerce de détail de pièces et accessoires de véhicules automobiles'),
  ('47.83Y', '47.83', '47.8', '47', 'G', 'COMMERCE', 'Commerce de détail de motocycles et de pièces et accessoires de motocycles'),
  ('47.91Y', '47.91', '47.9', '47', 'G', 'COMMERCE', 'Activités de service d''intermédiation pour le commerce de détail non spécialisé'),
  ('47.92G', '47.92', '47.9', '47', 'G', 'COMMERCE', 'Activités de service d''intermédiation pour le commerce de détail de véhicules automobiles'),
  ('47.92H', '47.92', '47.9', '47', 'G', 'COMMERCE', 'Activités de service d''intermédiation pour le commerce de détail de journaux et de produits à base de tabac'),
  ('47.92J', '47.92', '47.9', '47', 'G', 'COMMERCE', 'Activités de service d''intermédiation pour le commerce de détail spécialisé d''autres biens'),
  ('49.11Y', '49.11', '49.1', '49', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Transport ferroviaire lourd de voyageurs'),
  ('49.12Y', '49.12', '49.1', '49', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Autre transport ferroviaire de voyageurs'),
  ('49.20Y', '49.20', '49.2', '49', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Transport ferroviaire de fret'),
  ('49.31G', '49.31', '49.3', '49', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Transport régulier urbain et suburbain de voyageurs par route'),
  ('49.31H', '49.31', '49.3', '49', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Autre transport régulier de voyageurs par route'),
  ('49.32Y', '49.32', '49.3', '49', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Transport non régulier de voyageurs par route'),
  ('49.33G', '49.33', '49.3', '49', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Transport de personnes par taxi'),
  ('49.33H', '49.33', '49.3', '49', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Autre transport de personnes sur demande par véhicule avec chauffeur'),
  ('49.34Y', '49.34', '49.3', '49', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Transport de voyageurs par téléphériques et remontées mécaniques'),
  ('49.39Y', '49.39', '49.3', '49', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Autre transport terrestre de voyageurs n.c.a.'),
  ('49.41G', '49.41', '49.4', '49', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Transport routier de fret longue distance'),
  ('49.41H', '49.41', '49.4', '49', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Transport routier de fret régional et de proximité'),
  ('49.41J', '49.41', '49.4', '49', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Location de camions avec chauffeur'),
  ('49.42Y', '49.42', '49.4', '49', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Services de déménagement'),
  ('49.50Y', '49.50', '49.5', '49', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Transport par conduites'),
  ('50.10Y', '50.10', '50.1', '50', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Transports maritimes et côtiers de passagers'),
  ('50.20Y', '50.20', '50.2', '50', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Transports maritimes et côtiers de fret'),
  ('50.30Y', '50.30', '50.3', '50', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Transports fluviaux de passagers'),
  ('50.40Y', '50.40', '50.4', '50', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Transports fluviaux de fret'),
  ('51.10Y', '51.10', '51.1', '51', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Transports aériens de passagers'),
  ('51.21Y', '51.21', '51.2', '51', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Transports aériens de fret'),
  ('51.22Y', '51.22', '51.2', '51', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Transports spatiaux'),
  ('52.10G', '52.10', '52.1', '52', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Entreposage et stockage frigorifique'),
  ('52.10H', '52.10', '52.1', '52', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Entreposage et stockage non frigorifique'),
  ('52.21Y', '52.21', '52.2', '52', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Services auxiliaires des transports terrestres'),
  ('52.22Y', '52.22', '52.2', '52', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Services auxiliaires des transports par eau'),
  ('52.23Y', '52.23', '52.2', '52', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Services auxiliaires des transports aériens'),
  ('52.24G', '52.24', '52.2', '52', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Manutention portuaire'),
  ('52.24H', '52.24', '52.2', '52', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Manutention non portuaire'),
  ('52.25Y', '52.25', '52.2', '52', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Activités de service logistique'),
  ('52.26Y', '52.26', '52.2', '52', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Autres activités de soutien pour les transports'),
  ('52.31Y', '52.31', '52.3', '52', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Activités de service d''intermédiation pour le transport de fret'),
  ('52.32Y', '52.32', '52.3', '52', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Activités de service d''intermédiation pour le transport de passagers'),
  ('53.10Y', '53.10', '53.1', '53', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Activités de poste dans le cadre d''une obligation de service universel'),
  ('53.20G', '53.20', '53.2', '53', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Livraison de colis'),
  ('53.20H', '53.20', '53.2', '53', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Livraison à domicile de repas et autres activités de poste et de courrier n.c.a.'),
  ('53.30Y', '53.30', '53.3', '53', 'H', 'TRANSPORTS ET ENTREPOSAGE', 'Activités de service d''intermédiation pour des activités de poste et de courrier'),
  ('55.10Y', '55.10', '55.1', '55', 'I', 'HÉBERGEMENT ET RESTAURATION', 'Hôtels et hébergement similaire'),
  ('55.20Y', '55.20', '55.2', '55', 'I', 'HÉBERGEMENT ET RESTAURATION', 'Hébergement touristique et autre hébergement de courte durée'),
  ('55.30Y', '55.30', '55.3', '55', 'I', 'HÉBERGEMENT ET RESTAURATION', 'Terrains de camping et parcs pour caravanes ou véhicules de loisirs'),
  ('55.40Y', '55.40', '55.4', '55', 'I', 'HÉBERGEMENT ET RESTAURATION', 'Activités de service d''intermédiation pour l''hébergement'),
  ('55.90Y', '55.90', '55.9', '55', 'I', 'HÉBERGEMENT ET RESTAURATION', 'Autres hébergements'),
  ('56.11G', '56.11', '56.1', '56', 'I', 'HÉBERGEMENT ET RESTAURATION', 'Restauration traditionnelle'),
  ('56.11H', '56.11', '56.1', '56', 'I', 'HÉBERGEMENT ET RESTAURATION', 'Cafétérias et autres libres services'),
  ('56.11J', '56.11', '56.1', '56', 'I', 'HÉBERGEMENT ET RESTAURATION', 'Restauration de type rapide'),
  ('56.12Y', '56.12', '56.1', '56', 'I', 'HÉBERGEMENT ET RESTAURATION', 'Activités de service de restauration mobile'),
  ('56.21Y', '56.21', '56.2', '56', 'I', 'HÉBERGEMENT ET RESTAURATION', 'Activités de traiteur événementiel'),
  ('56.22Y', '56.22', '56.2', '56', 'I', 'HÉBERGEMENT ET RESTAURATION', 'Activités de service contractuel de restauration et autres activités de service de restauration'),
  ('56.30Y', '56.30', '56.3', '56', 'I', 'HÉBERGEMENT ET RESTAURATION', 'Activités de débit de boissons'),
  ('56.40Y', '56.40', '56.4', '56', 'I', 'HÉBERGEMENT ET RESTAURATION', 'Activités de service d''intermédiation pour des activités de service de restauration'),
  ('58.11Y', '58.11', '58.1', '58', 'J', 'ÉDITION, DIFFUSION ET ACTIVITÉS DE PRODUCTION ET DE DISTRIBUTION DE CONTENU', 'Édition de livres'),
  ('58.12Y', '58.12', '58.1', '58', 'J', 'ÉDITION, DIFFUSION ET ACTIVITÉS DE PRODUCTION ET DE DISTRIBUTION DE CONTENU', 'Édition de journaux'),
  ('58.13Y', '58.13', '58.1', '58', 'J', 'ÉDITION, DIFFUSION ET ACTIVITÉS DE PRODUCTION ET DE DISTRIBUTION DE CONTENU', 'Édition de revues et de périodiques'),
  ('58.19Y', '58.19', '58.1', '58', 'J', 'ÉDITION, DIFFUSION ET ACTIVITÉS DE PRODUCTION ET DE DISTRIBUTION DE CONTENU', 'Autres activités d''édition, à l''exception de l''édition de logiciels'),
  ('58.21Y', '58.21', '58.2', '58', 'J', 'ÉDITION, DIFFUSION ET ACTIVITÉS DE PRODUCTION ET DE DISTRIBUTION DE CONTENU', 'Édition de jeux vidéo'),
  ('58.29Y', '58.29', '58.2', '58', 'J', 'ÉDITION, DIFFUSION ET ACTIVITÉS DE PRODUCTION ET DE DISTRIBUTION DE CONTENU', 'Édition d''autres logiciels'),
  ('59.11G', '59.11', '59.1', '59', 'J', 'ÉDITION, DIFFUSION ET ACTIVITÉS DE PRODUCTION ET DE DISTRIBUTION DE CONTENU', 'Production de films et programmes audiovisuels'),
  ('59.11H', '59.11', '59.1', '59', 'J', 'ÉDITION, DIFFUSION ET ACTIVITÉS DE PRODUCTION ET DE DISTRIBUTION DE CONTENU', 'Production de films institutionnels et publicitaires'),
  ('59.11J', '59.11', '59.1', '59', 'J', 'ÉDITION, DIFFUSION ET ACTIVITÉS DE PRODUCTION ET DE DISTRIBUTION DE CONTENU', 'Production de films pour le cinéma'),
  ('59.11K', '59.11', '59.1', '59', 'J', 'ÉDITION, DIFFUSION ET ACTIVITÉS DE PRODUCTION ET DE DISTRIBUTION DE CONTENU', 'Production de films et programmes d''animation'),
  ('59.12Y', '59.12', '59.1', '59', 'J', 'ÉDITION, DIFFUSION ET ACTIVITÉS DE PRODUCTION ET DE DISTRIBUTION DE CONTENU', 'Post-production de films cinématographiques, de vidéos et de programmes de télévision'),
  ('59.13Y', '59.13', '59.1', '59', 'J', 'ÉDITION, DIFFUSION ET ACTIVITÉS DE PRODUCTION ET DE DISTRIBUTION DE CONTENU', 'Distribution de films cinématographiques et de vidéos'),
  ('59.14Y', '59.14', '59.1', '59', 'J', 'ÉDITION, DIFFUSION ET ACTIVITÉS DE PRODUCTION ET DE DISTRIBUTION DE CONTENU', 'Projection de films cinématographiques'),
  ('59.20Y', '59.20', '59.2', '59', 'J', 'ÉDITION, DIFFUSION ET ACTIVITÉS DE PRODUCTION ET DE DISTRIBUTION DE CONTENU', 'Enregistrement sonore et édition musicale'),
  ('60.10Y', '60.10', '60.1', '60', 'J', 'ÉDITION, DIFFUSION ET ACTIVITÉS DE PRODUCTION ET DE DISTRIBUTION DE CONTENU', 'Radiodiffusion et activités de distribution de contenu audio'),
  ('60.20G', '60.20', '60.2', '60', 'J', 'ÉDITION, DIFFUSION ET ACTIVITÉS DE PRODUCTION ET DE DISTRIBUTION DE CONTENU', 'Programmation de télévision et télédiffusion'),
  ('60.20H', '60.20', '60.2', '60', 'J', 'ÉDITION, DIFFUSION ET ACTIVITÉS DE PRODUCTION ET DE DISTRIBUTION DE CONTENU', 'Édition de services de médias à la demande'),
  ('60.31Y', '60.31', '60.3', '60', 'J', 'ÉDITION, DIFFUSION ET ACTIVITÉS DE PRODUCTION ET DE DISTRIBUTION DE CONTENU', 'Activités d''agence de presse'),
  ('60.39Y', '60.39', '60.3', '60', 'J', 'ÉDITION, DIFFUSION ET ACTIVITÉS DE PRODUCTION ET DE DISTRIBUTION DE CONTENU', 'Autres activités de distribution de contenu'),
  ('61.10Y', '61.10', '61.1', '61', 'K', 'TÉLÉCOMMUNICATIONS, PROGRAMMATION INFORMATIQUE, CONSEIL, INFRASTRUCTURE INFORMATIQUE ET AUTRES ACTIVITÉS DE SERVICE INFORMATIQUE', 'Activités de télécommunications filaires, sans fil et satellitaires'),
  ('61.20Y', '61.20', '61.2', '61', 'K', 'TÉLÉCOMMUNICATIONS, PROGRAMMATION INFORMATIQUE, CONSEIL, INFRASTRUCTURE INFORMATIQUE ET AUTRES ACTIVITÉS DE SERVICE INFORMATIQUE', 'Activités de revente de télécommunications et activités de service d''intermédiation pour les télécommunications'),
  ('61.90Y', '61.90', '61.9', '61', 'K', 'TÉLÉCOMMUNICATIONS, PROGRAMMATION INFORMATIQUE, CONSEIL, INFRASTRUCTURE INFORMATIQUE ET AUTRES ACTIVITÉS DE SERVICE INFORMATIQUE', 'Autres activités de télécommunications'),
  ('62.10Y', '62.10', '62.1', '62', 'K', 'TÉLÉCOMMUNICATIONS, PROGRAMMATION INFORMATIQUE, CONSEIL, INFRASTRUCTURE INFORMATIQUE ET AUTRES ACTIVITÉS DE SERVICE INFORMATIQUE', 'Activités de programmation informatique'),
  ('62.20G', '62.20', '62.2', '62', 'K', 'TÉLÉCOMMUNICATIONS, PROGRAMMATION INFORMATIQUE, CONSEIL, INFRASTRUCTURE INFORMATIQUE ET AUTRES ACTIVITÉS DE SERVICE INFORMATIQUE', 'Conseil en systèmes et logiciels informatiques'),
  ('62.20H', '62.20', '62.2', '62', 'K', 'TÉLÉCOMMUNICATIONS, PROGRAMMATION INFORMATIQUE, CONSEIL, INFRASTRUCTURE INFORMATIQUE ET AUTRES ACTIVITÉS DE SERVICE INFORMATIQUE', 'Gestion d''installations informatiques et maintenance de systèmes et d''applications informatiques'),
  ('62.90Y', '62.90', '62.9', '62', 'K', 'TÉLÉCOMMUNICATIONS, PROGRAMMATION INFORMATIQUE, CONSEIL, INFRASTRUCTURE INFORMATIQUE ET AUTRES ACTIVITÉS DE SERVICE INFORMATIQUE', 'Autres activités de service informatique'),
  ('63.10Y', '63.10', '63.1', '63', 'K', 'TÉLÉCOMMUNICATIONS, PROGRAMMATION INFORMATIQUE, CONSEIL, INFRASTRUCTURE INFORMATIQUE ET AUTRES ACTIVITÉS DE SERVICE INFORMATIQUE', 'Infrastructure informatique, traitement de données, hébergement et activités connexes'),
  ('63.91Y', '63.91', '63.9', '63', 'K', 'TÉLÉCOMMUNICATIONS, PROGRAMMATION INFORMATIQUE, CONSEIL, INFRASTRUCTURE INFORMATIQUE ET AUTRES ACTIVITÉS DE SERVICE INFORMATIQUE', 'Activités de portail de recherche sur le web'),
  ('63.92Y', '63.92', '63.9', '63', 'K', 'TÉLÉCOMMUNICATIONS, PROGRAMMATION INFORMATIQUE, CONSEIL, INFRASTRUCTURE INFORMATIQUE ET AUTRES ACTIVITÉS DE SERVICE INFORMATIQUE', 'Autres activités de service d''information'),
  ('64.11Y', '64.11', '64.1', '64', 'L', 'ACTIVITÉS FINANCIÈRES ET D''ASSURANCE', 'Activités de banque centrale'),
  ('64.19Y', '64.19', '64.1', '64', 'L', 'ACTIVITÉS FINANCIÈRES ET D''ASSURANCE', 'Autre intermédiation monétaire'),
  ('64.21Y', '64.21', '64.2', '64', 'L', 'ACTIVITÉS FINANCIÈRES ET D''ASSURANCE', 'Activités de société holding'),
  ('64.22Y', '64.22', '64.2', '64', 'L', 'ACTIVITÉS FINANCIÈRES ET D''ASSURANCE', 'Activités de conduit de financement'),
  ('64.31Y', '64.31', '64.3', '64', 'L', 'ACTIVITÉS FINANCIÈRES ET D''ASSURANCE', 'Activités de fonds d''investissement sur le marché monétaire ou non monétaire'),
  ('64.32Y', '64.32', '64.3', '64', 'L', 'ACTIVITÉS FINANCIÈRES ET D''ASSURANCE', 'Activités de fiducie, comptes de patrimoine et d''agence'),
  ('64.91Y', '64.91', '64.9', '64', 'L', 'ACTIVITÉS FINANCIÈRES ET D''ASSURANCE', 'Crédit-bail'),
  ('64.92Y', '64.92', '64.9', '64', 'L', 'ACTIVITÉS FINANCIÈRES ET D''ASSURANCE', 'Autre distribution de crédit'),
  ('64.99Y', '64.99', '64.9', '64', 'L', 'ACTIVITÉS FINANCIÈRES ET D''ASSURANCE', 'Autres activités des services financiers, hors assurance et fonds de pension, n.c.a.'),
  ('65.11Y', '65.11', '65.1', '65', 'L', 'ACTIVITÉS FINANCIÈRES ET D''ASSURANCE', 'Assurance vie'),
  ('65.12Y', '65.12', '65.1', '65', 'L', 'ACTIVITÉS FINANCIÈRES ET D''ASSURANCE', 'Assurances non-vie'),
  ('65.20Y', '65.20', '65.2', '65', 'L', 'ACTIVITÉS FINANCIÈRES ET D''ASSURANCE', 'Réassurance'),
  ('65.30Y', '65.30', '65.3', '65', 'L', 'ACTIVITÉS FINANCIÈRES ET D''ASSURANCE', 'Fonds de pension'),
  ('66.11Y', '66.11', '66.1', '66', 'L', 'ACTIVITÉS FINANCIÈRES ET D''ASSURANCE', 'Administration de marchés financiers'),
  ('66.12Y', '66.12', '66.1', '66', 'L', 'ACTIVITÉS FINANCIÈRES ET D''ASSURANCE', 'Courtage de valeurs mobilières et de matières premières'),
  ('66.19G', '66.19', '66.1', '66', 'L', 'ACTIVITÉS FINANCIÈRES ET D''ASSURANCE', 'Activités des unités non productives détentrices de patrimoine mobilier'),
  ('66.19H', '66.19', '66.1', '66', 'L', 'ACTIVITÉS FINANCIÈRES ET D''ASSURANCE', 'Autres activités auxiliaires de services financiers, hors assurance et caisses de retraite, n.c.a.'),
  ('66.21Y', '66.21', '66.2', '66', 'L', 'ACTIVITÉS FINANCIÈRES ET D''ASSURANCE', 'Évaluation des risques et dommages'),
  ('66.22Y', '66.22', '66.2', '66', 'L', 'ACTIVITÉS FINANCIÈRES ET D''ASSURANCE', 'Activités des agents et courtiers d''assurances'),
  ('66.29Y', '66.29', '66.2', '66', 'L', 'ACTIVITÉS FINANCIÈRES ET D''ASSURANCE', 'Activités auxiliaires d''assurance et de fonds de pension n.c.a.'),
  ('66.30Y', '66.30', '66.3', '66', 'L', 'ACTIVITÉS FINANCIÈRES ET D''ASSURANCE', 'Activités de gestion de fonds'),
  ('68.11Y', '68.11', '68.1', '68', 'M', 'ACTIVITÉS IMMOBILIÈRES', 'Achat et vente de biens propres'),
  ('68.12Y', '68.12', '68.1', '68', 'M', 'ACTIVITÉS IMMOBILIÈRES', 'Promotion immobilière'),
  ('68.20G', '68.20', '68.2', '68', 'M', 'ACTIVITÉS IMMOBILIÈRES', 'Location de logements'),
  ('68.20H', '68.20', '68.2', '68', 'M', 'ACTIVITÉS IMMOBILIÈRES', 'Location et exploitation d''autres biens immobiliers propres ou loués'),
  ('68.31Y', '68.31', '68.3', '68', 'M', 'ACTIVITÉS IMMOBILIÈRES', 'Activités de service d''intermédiation pour les activités immobilières'),
  ('68.32G', '68.32', '68.3', '68', 'M', 'ACTIVITÉS IMMOBILIÈRES', 'Activités des unités non productives détentrices de patrimoine immobilier'),
  ('68.32H', '68.32', '68.3', '68', 'M', 'ACTIVITÉS IMMOBILIÈRES', 'Autres activités immobilières pour compte de tiers n.c.a.'),
  ('69.10Y', '69.10', '69.1', '69', 'N', 'ACTIVITÉS SPÉCIALISÉES, SCIENTIFIQUES ET TECHNIQUES', 'Activités juridiques'),
  ('69.20Y', '69.20', '69.2', '69', 'N', 'ACTIVITÉS SPÉCIALISÉES, SCIENTIFIQUES ET TECHNIQUES', 'Activités de comptabilité, de tenue de comptes et d''audit ; conseil fiscal'),
  ('70.10Y', '70.10', '70.1', '70', 'N', 'ACTIVITÉS SPÉCIALISÉES, SCIENTIFIQUES ET TECHNIQUES', 'Activités des sièges sociaux'),
  ('70.20Y', '70.20', '70.2', '70', 'N', 'ACTIVITÉS SPÉCIALISÉES, SCIENTIFIQUES ET TECHNIQUES', 'Activités de conseil pour les affaires et autre conseil de gestion'),
  ('71.11Y', '71.11', '71.1', '71', 'N', 'ACTIVITÉS SPÉCIALISÉES, SCIENTIFIQUES ET TECHNIQUES', 'Activités d''architecture'),
  ('71.12Y', '71.12', '71.1', '71', 'N', 'ACTIVITÉS SPÉCIALISÉES, SCIENTIFIQUES ET TECHNIQUES', 'Activités d''ingénierie et de conseil technique connexe'),
  ('71.20G', '71.20', '71.2', '71', 'N', 'ACTIVITÉS SPÉCIALISÉES, SCIENTIFIQUES ET TECHNIQUES', 'Contrôle technique des véhicules'),
  ('71.20H', '71.20', '71.2', '71', 'N', 'ACTIVITÉS SPÉCIALISÉES, SCIENTIFIQUES ET TECHNIQUES', 'Analyses, essais et inspections techniques'),
  ('72.10G', '72.10', '72.1', '72', 'N', 'ACTIVITÉS SPÉCIALISÉES, SCIENTIFIQUES ET TECHNIQUES', 'Recherche et développement en biotechnologies'),
  ('72.10H', '72.10', '72.1', '72', 'N', 'ACTIVITÉS SPÉCIALISÉES, SCIENTIFIQUES ET TECHNIQUES', 'Recherche et développement en autres sciences physiques et naturelles'),
  ('72.20Y', '72.20', '72.2', '72', 'N', 'ACTIVITÉS SPÉCIALISÉES, SCIENTIFIQUES ET TECHNIQUES', 'Recherche et développement en sciences humaines et sociales'),
  ('73.11Y', '73.11', '73.1', '73', 'N', 'ACTIVITÉS SPÉCIALISÉES, SCIENTIFIQUES ET TECHNIQUES', 'Activités d''agence de publicité'),
  ('73.12Y', '73.12', '73.1', '73', 'N', 'ACTIVITÉS SPÉCIALISÉES, SCIENTIFIQUES ET TECHNIQUES', 'Régie publicitaire de médias'),
  ('73.20Y', '73.20', '73.2', '73', 'N', 'ACTIVITÉS SPÉCIALISÉES, SCIENTIFIQUES ET TECHNIQUES', 'Études de marché et sondages'),
  ('73.30Y', '73.30', '73.3', '73', 'N', 'ACTIVITÉS SPÉCIALISÉES, SCIENTIFIQUES ET TECHNIQUES', 'Activités de relations publiques et de communication'),
  ('74.11Y', '74.11', '74.1', '74', 'N', 'ACTIVITÉS SPÉCIALISÉES, SCIENTIFIQUES ET TECHNIQUES', 'Activités de design pour la création de mode ou les produits industriels'),
  ('74.12Y', '74.12', '74.1', '74', 'N', 'ACTIVITÉS SPÉCIALISÉES, SCIENTIFIQUES ET TECHNIQUES', 'Activités de design graphique et de communication visuelle'),
  ('74.13Y', '74.13', '74.1', '74', 'N', 'ACTIVITÉS SPÉCIALISÉES, SCIENTIFIQUES ET TECHNIQUES', 'Activités de design d''intérieur'),
  ('74.14Y', '74.14', '74.1', '74', 'N', 'ACTIVITÉS SPÉCIALISÉES, SCIENTIFIQUES ET TECHNIQUES', 'Autres activités spécialisées de design'),
  ('74.20Y', '74.20', '74.2', '74', 'N', 'ACTIVITÉS SPÉCIALISÉES, SCIENTIFIQUES ET TECHNIQUES', 'Activités photographiques'),
  ('74.30Y', '74.30', '74.3', '74', 'N', 'ACTIVITÉS SPÉCIALISÉES, SCIENTIFIQUES ET TECHNIQUES', 'Activités de traduction et d''interprétation'),
  ('74.91Y', '74.91', '74.9', '74', 'N', 'ACTIVITÉS SPÉCIALISÉES, SCIENTIFIQUES ET TECHNIQUES', 'Activités de courtage et de marketing de brevets'),
  ('74.99Y', '74.99', '74.9', '74', 'N', 'ACTIVITÉS SPÉCIALISÉES, SCIENTIFIQUES ET TECHNIQUES', 'Toutes les autres activités spécialisées, scientifiques et techniques n.c.a.'),
  ('75.00Y', '75.00', '75.0', '75', 'N', 'ACTIVITÉS SPÉCIALISÉES, SCIENTIFIQUES ET TECHNIQUES', 'Activités vétérinaires'),
  ('77.11Y', '77.11', '77.1', '77', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Location et location-bail de voitures et véhicules automobiles légers'),
  ('77.12Y', '77.12', '77.1', '77', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Location et location-bail de camions'),
  ('77.21Y', '77.21', '77.2', '77', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Location et location-bail d''articles de loisirs et de sport'),
  ('77.22Y', '77.22', '77.2', '77', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Location et location-bail d''autres biens personnels et domestiques'),
  ('77.31Y', '77.31', '77.3', '77', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Location et location-bail de matériel agricole'),
  ('77.32Y', '77.32', '77.3', '77', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Location et location-bail de machines et équipements pour la construction et le génie civil'),
  ('77.33Y', '77.33', '77.3', '77', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Location et location-bail de machines et équipements de bureau et d''ordinateurs'),
  ('77.34Y', '77.34', '77.3', '77', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Location et location-bail de matériels de transport par eau'),
  ('77.35Y', '77.35', '77.3', '77', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Location et location-bail de matériels de transport aérien'),
  ('77.39Y', '77.39', '77.3', '77', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Location et location-bail d''autres machines, équipements et biens n.c.a.'),
  ('77.40G', '77.40', '77.4', '77', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Services de franchise ou de licence de marques'),
  ('77.40H', '77.40', '77.4', '77', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Autre location-bail de propriété intellectuelle et de produits similaires, à l''exception des œuvres soumises à copyright'),
  ('77.51Y', '77.51', '77.5', '77', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Activités de service d''intermédiation pour la location et la location-bail de voitures, camping-cars et caravanes'),
  ('77.52Y', '77.52', '77.5', '77', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Activités de service d''intermédiation pour la location et la location-bail d''autres biens corporels et d''immobilisations incorporelles non financières'),
  ('78.10Y', '78.10', '78.1', '78', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Activités des agences de placement de main-d''œuvre'),
  ('78.20G', '78.20', '78.2', '78', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Activités d''agence de travail temporaire'),
  ('78.20H', '78.20', '78.2', '78', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Autre mise à disposition de ressources humaines'),
  ('79.11Y', '79.11', '79.1', '79', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Activités d''agence de voyage'),
  ('79.12Y', '79.12', '79.1', '79', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Activités de voyagiste'),
  ('79.90Y', '79.90', '79.9', '79', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Autres activités de service de réservation et activités connexes'),
  ('80.01Y', '80.01', '80.0', '80', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Activités d''investigation et de sécurité privée'),
  ('80.09Y', '80.09', '80.0', '80', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Activités de sécurité n.c.a.'),
  ('81.10Y', '81.10', '81.1', '81', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Activités de soutien combinées pour les installations'),
  ('81.21Y', '81.21', '81.2', '81', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Nettoyage courant des bâtiments'),
  ('81.22Y', '81.22', '81.2', '81', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Autres activités de nettoyage des bâtiments et nettoyage industriel'),
  ('81.23G', '81.23', '81.2', '81', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Désinfection, désinsectisation, dératisation'),
  ('81.23H', '81.23', '81.2', '81', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Autres activités de nettoyage n.c.a.'),
  ('81.30Y', '81.30', '81.3', '81', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Activités de service d''aménagement paysager'),
  ('82.10Y', '82.10', '82.1', '82', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Activités de service de bureau et de soutien administratif'),
  ('82.20Y', '82.20', '82.2', '82', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Activités de centre d''appels'),
  ('82.30Y', '82.30', '82.3', '82', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Organisation de salons professionnels et congrès'),
  ('82.40Y', '82.40', '82.4', '82', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Activités de service d''intermédiation pour des services de soutien aux entreprises n.c.a.'),
  ('82.91Y', '82.91', '82.9', '82', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Activités d''agence de recouvrement et de bureau de crédit'),
  ('82.92Y', '82.92', '82.9', '82', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Activités de conditionnement'),
  ('82.99Y', '82.99', '82.9', '82', 'O', 'ACTIVITÉS DE SERVICE ADMINISTRATIF ET DE SOUTIEN', 'Autres activités de service de soutien aux entreprises n.c.a.'),
  ('84.11Y', '84.11', '84.1', '84', 'P', 'ADMINISTRATION PUBLIQUE ET DÉFENSE ; SÉCURITÉ SOCIALE OBLIGATOIRE', 'Activités d''administration publique générale'),
  ('84.12Y', '84.12', '84.1', '84', 'P', 'ADMINISTRATION PUBLIQUE ET DÉFENSE ; SÉCURITÉ SOCIALE OBLIGATOIRE', 'Réglementation des soins de santé, de l''enseignement, des services culturels et des autres services sociaux'),
  ('84.13Y', '84.13', '84.1', '84', 'P', 'ADMINISTRATION PUBLIQUE ET DÉFENSE ; SÉCURITÉ SOCIALE OBLIGATOIRE', 'Réglementation et contribution à l''amélioration de l''efficacité des activités économiques'),
  ('84.21Y', '84.21', '84.2', '84', 'P', 'ADMINISTRATION PUBLIQUE ET DÉFENSE ; SÉCURITÉ SOCIALE OBLIGATOIRE', 'Affaires étrangères'),
  ('84.22Y', '84.22', '84.2', '84', 'P', 'ADMINISTRATION PUBLIQUE ET DÉFENSE ; SÉCURITÉ SOCIALE OBLIGATOIRE', 'Défense'),
  ('84.23Y', '84.23', '84.2', '84', 'P', 'ADMINISTRATION PUBLIQUE ET DÉFENSE ; SÉCURITÉ SOCIALE OBLIGATOIRE', 'Justice'),
  ('84.24Y', '84.24', '84.2', '84', 'P', 'ADMINISTRATION PUBLIQUE ET DÉFENSE ; SÉCURITÉ SOCIALE OBLIGATOIRE', 'Activités d''ordre public et de sécurité civile'),
  ('84.25Y', '84.25', '84.2', '84', 'P', 'ADMINISTRATION PUBLIQUE ET DÉFENSE ; SÉCURITÉ SOCIALE OBLIGATOIRE', 'Activités de service d''incendie et de secours'),
  ('84.30G', '84.30', '84.3', '84', 'P', 'ADMINISTRATION PUBLIQUE ET DÉFENSE ; SÉCURITÉ SOCIALE OBLIGATOIRE', 'Activités générales de sécurité sociale'),
  ('84.30H', '84.30', '84.3', '84', 'P', 'ADMINISTRATION PUBLIQUE ET DÉFENSE ; SÉCURITÉ SOCIALE OBLIGATOIRE', 'Gestion des retraites complémentaires'),
  ('84.30J', '84.30', '84.3', '84', 'P', 'ADMINISTRATION PUBLIQUE ET DÉFENSE ; SÉCURITÉ SOCIALE OBLIGATOIRE', 'Distribution sociale de revenus'),
  ('85.10Y', '85.10', '85.1', '85', 'Q', 'ENSEIGNEMENT', 'Enseignement pré-primaire'),
  ('85.20Y', '85.20', '85.2', '85', 'Q', 'ENSEIGNEMENT', 'Enseignement primaire'),
  ('85.31Y', '85.31', '85.3', '85', 'Q', 'ENSEIGNEMENT', 'Enseignement secondaire général'),
  ('85.32Y', '85.32', '85.3', '85', 'Q', 'ENSEIGNEMENT', 'Enseignement secondaire professionnel'),
  ('85.33Y', '85.33', '85.3', '85', 'Q', 'ENSEIGNEMENT', 'Enseignement post-secondaire non supérieur'),
  ('85.40Y', '85.40', '85.4', '85', 'Q', 'ENSEIGNEMENT', 'Enseignement supérieur'),
  ('85.51Y', '85.51', '85.5', '85', 'Q', 'ENSEIGNEMENT', 'Enseignement de disciplines sportives et d''activités de loisirs'),
  ('85.52Y', '85.52', '85.5', '85', 'Q', 'ENSEIGNEMENT', 'Enseignement culturel'),
  ('85.53Y', '85.53', '85.5', '85', 'Q', 'ENSEIGNEMENT', 'Enseignement de la conduite'),
  ('85.59G', '85.59', '85.5', '85', 'Q', 'ENSEIGNEMENT', 'Formation continue d''adultes'),
  ('85.59H', '85.59', '85.5', '85', 'Q', 'ENSEIGNEMENT', 'Tous les autres enseignements n.c.a.'),
  ('85.61Y', '85.61', '85.6', '85', 'Q', 'ENSEIGNEMENT', 'Activités de service d''intermédiation dans le domaine de l''appui scolaire et du tutorat'),
  ('85.69Y', '85.69', '85.6', '85', 'Q', 'ENSEIGNEMENT', 'Activités de soutien à l''enseignement n.c.a.'),
  ('86.10Y', '86.10', '86.1', '86', 'R', 'SANTÉ HUMAINE ET ACTIVITÉS D''ACTION SOCIALE', 'Activités hospitalières'),
  ('86.21Y', '86.21', '86.2', '86', 'R', 'SANTÉ HUMAINE ET ACTIVITÉS D''ACTION SOCIALE', 'Activités de médecine générale'),
  ('86.22Y', '86.22', '86.2', '86', 'R', 'SANTÉ HUMAINE ET ACTIVITÉS D''ACTION SOCIALE', 'Activités de médecine spécialisée'),
  ('86.23Y', '86.23', '86.2', '86', 'R', 'SANTÉ HUMAINE ET ACTIVITÉS D''ACTION SOCIALE', 'Activités de soins dentaires'),
  ('86.91Y', '86.91', '86.9', '86', 'R', 'SANTÉ HUMAINE ET ACTIVITÉS D''ACTION SOCIALE', 'Activités d''imagerie médicale et de laboratoire d''analyse médicale'),
  ('86.92Y', '86.92', '86.9', '86', 'R', 'SANTÉ HUMAINE ET ACTIVITÉS D''ACTION SOCIALE', 'Transport de patients par ambulance'),
  ('86.93Y', '86.93', '86.9', '86', 'R', 'SANTÉ HUMAINE ET ACTIVITÉS D''ACTION SOCIALE', 'Activités des psychologues et psychothérapeutes, à l''exception des médecins'),
  ('86.94G', '86.94', '86.9', '86', 'R', 'SANTÉ HUMAINE ET ACTIVITÉS D''ACTION SOCIALE', 'Activités de soins infirmiers'),
  ('86.94H', '86.94', '86.9', '86', 'R', 'SANTÉ HUMAINE ET ACTIVITÉS D''ACTION SOCIALE', 'Activités de maïeutique'),
  ('86.95Y', '86.95', '86.9', '86', 'R', 'SANTÉ HUMAINE ET ACTIVITÉS D''ACTION SOCIALE', 'Activités de physiothérapie'),
  ('86.96Y', '86.96', '86.9', '86', 'R', 'SANTÉ HUMAINE ET ACTIVITÉS D''ACTION SOCIALE', 'Activités de médecine traditionnelle, complémentaire et alternative'),
  ('86.97Y', '86.97', '86.9', '86', 'R', 'SANTÉ HUMAINE ET ACTIVITÉS D''ACTION SOCIALE', 'Activités de service d''intermédiation pour les services médicaux, dentaires et autres services pour la santé humaine'),
  ('86.99Y', '86.99', '86.9', '86', 'R', 'SANTÉ HUMAINE ET ACTIVITÉS D''ACTION SOCIALE', 'Autres activités pour la santé humaine n.c.a.'),
  ('87.10G', '87.10', '87.1', '87', 'R', 'SANTÉ HUMAINE ET ACTIVITÉS D''ACTION SOCIALE', 'Activités d''hébergement médicalisé pour personnes âgées'),
  ('87.10H', '87.10', '87.1', '87', 'R', 'SANTÉ HUMAINE ET ACTIVITÉS D''ACTION SOCIALE', 'Activités d''hébergement médicalisé pour enfants en situation de handicap'),
  ('87.10J', '87.10', '87.1', '87', 'R', 'SANTÉ HUMAINE ET ACTIVITÉS D''ACTION SOCIALE', 'Activités d''hébergement médicalisé pour adultes en situation de handicap et autres activités d''hébergement médicalisé'),
  ('87.20G', '87.20', '87.2', '87', 'R', 'SANTÉ HUMAINE ET ACTIVITÉS D''ACTION SOCIALE', 'Activités d''hébergement social pour personnes souffrant de maladie mentale'),
  ('87.20H', '87.20', '87.2', '87', 'R', 'SANTÉ HUMAINE ET ACTIVITÉS D''ACTION SOCIALE', 'Activités d''hébergement social pour personnes souffrant de toxicomanie'),
  ('87.30G', '87.30', '87.3', '87', 'R', 'SANTÉ HUMAINE ET ACTIVITÉS D''ACTION SOCIALE', 'Activités d''hébergement social pour personnes âgées'),
  ('87.30H', '87.30', '87.3', '87', 'R', 'SANTÉ HUMAINE ET ACTIVITÉS D''ACTION SOCIALE', 'Activités d''hébergement social pour personnes en situation de handicap physique'),
  ('87.91Y', '87.91', '87.9', '87', 'R', 'SANTÉ HUMAINE ET ACTIVITÉS D''ACTION SOCIALE', 'Activités de service d''intermédiation pour des activités de soins en établissement résidentiel'),
  ('87.99G', '87.99', '87.9', '87', 'R', 'SANTÉ HUMAINE ET ACTIVITÉS D''ACTION SOCIALE', 'Activités d''hébergement social pour enfants en difficulté'),
  ('87.99H', '87.99', '87.9', '87', 'R', 'SANTÉ HUMAINE ET ACTIVITÉS D''ACTION SOCIALE', 'Activités d''hébergement social pour adultes et familles en difficulté et autres activités d''hébergement social n.c.a.'),
  ('88.10G', '88.10', '88.1', '88', 'R', 'SANTÉ HUMAINE ET ACTIVITÉS D''ACTION SOCIALE', 'Activités d''action sociale à domicile'),
  ('88.10H', '88.10', '88.1', '88', 'R', 'SANTÉ HUMAINE ET ACTIVITÉS D''ACTION SOCIALE', 'Activités d''accueil ou d''accompagnement sans hébergement d''adultes en situation de handicap ou de personnes âgées'),
  ('88.10J', '88.10', '88.1', '88', 'R', 'SANTÉ HUMAINE ET ACTIVITÉS D''ACTION SOCIALE', 'Activités de réadaptation professionnelle et réinsertion, aide par le travail'),
  ('88.91G', '88.91', '88.9', '88', 'R', 'SANTÉ HUMAINE ET ACTIVITÉS D''ACTION SOCIALE', 'Accueil de jeunes enfants en structure collective'),
  ('88.91H', '88.91', '88.9', '88', 'R', 'SANTÉ HUMAINE ET ACTIVITÉS D''ACTION SOCIALE', 'Accueil de jeunes enfants à domicile'),
  ('88.91J', '88.91', '88.9', '88', 'R', 'SANTÉ HUMAINE ET ACTIVITÉS D''ACTION SOCIALE', 'Accueil ou accompagnement sans hébergement d''enfants en situation de handicap'),
  ('88.99G', '88.99', '88.9', '88', 'R', 'SANTÉ HUMAINE ET ACTIVITÉS D''ACTION SOCIALE', 'Autre accueil ou accompagnement sans hébergement d''enfants et d''adolescents'),
  ('88.99H', '88.99', '88.9', '88', 'R', 'SANTÉ HUMAINE ET ACTIVITÉS D''ACTION SOCIALE', 'Toutes les autres activités d''action sociale sans hébergement n.c.a.'),
  ('90.11Y', '90.11', '90.1', '90', 'S', 'ARTS, SPORTS ET ACTIVITÉS RÉCRÉATIVES', 'Activités de création littéraire et de composition musicale'),
  ('90.12Y', '90.12', '90.1', '90', 'S', 'ARTS, SPORTS ET ACTIVITÉS RÉCRÉATIVES', 'Activités de création en arts visuels'),
  ('90.13Y', '90.13', '90.1', '90', 'S', 'ARTS, SPORTS ET ACTIVITÉS RÉCRÉATIVES', 'Autres activités de création artistique'),
  ('90.20Y', '90.20', '90.2', '90', 'S', 'ARTS, SPORTS ET ACTIVITÉS RÉCRÉATIVES', 'Activités de spectacle'),
  ('90.31G', '90.31', '90.3', '90', 'S', 'ARTS, SPORTS ET ACTIVITÉS RÉCRÉATIVES', 'Gestion d''installations et de lieux de production et de diffusion des arts visuels'),
  ('90.31H', '90.31', '90.3', '90', 'S', 'ARTS, SPORTS ET ACTIVITÉS RÉCRÉATIVES', 'Gestion de salles de spectacle vivant'),
  ('90.39G', '90.39', '90.3', '90', 'S', 'ARTS, SPORTS ET ACTIVITÉS RÉCRÉATIVES', 'Activités de production et organisation d''évènements culturels'),
  ('90.39H', '90.39', '90.3', '90', 'S', 'ARTS, SPORTS ET ACTIVITÉS RÉCRÉATIVES', 'Activités de soutien technique aux spectacles et aux événements culturels'),
  ('91.11Y', '91.11', '91.1', '91', 'S', 'ARTS, SPORTS ET ACTIVITÉS RÉCRÉATIVES', 'Activités des bibliothèques'),
  ('91.12Y', '91.12', '91.1', '91', 'S', 'ARTS, SPORTS ET ACTIVITÉS RÉCRÉATIVES', 'Activités des centres d''archives'),
  ('91.21Y', '91.21', '91.2', '91', 'S', 'ARTS, SPORTS ET ACTIVITÉS RÉCRÉATIVES', 'Activités des musées et collections'),
  ('91.22Y', '91.22', '91.2', '91', 'S', 'ARTS, SPORTS ET ACTIVITÉS RÉCRÉATIVES', 'Activité des monuments et sites historiques'),
  ('91.30Y', '91.30', '91.3', '91', 'S', 'ARTS, SPORTS ET ACTIVITÉS RÉCRÉATIVES', 'Conservation, restauration et autres activités de soutien pour la préservation du patrimoine culturel'),
  ('91.41Y', '91.41', '91.4', '91', 'S', 'ARTS, SPORTS ET ACTIVITÉS RÉCRÉATIVES', 'Activités de gestion de jardins botaniques et zoologiques'),
  ('91.42Y', '91.42', '91.4', '91', 'S', 'ARTS, SPORTS ET ACTIVITÉS RÉCRÉATIVES', 'Activités de gestion de réserves naturelles'),
  ('92.00Y', '92.00', '92.0', '92', 'S', 'ARTS, SPORTS ET ACTIVITÉS RÉCRÉATIVES', 'Activités de jeux d''argent et de paris'),
  ('93.11Y', '93.11', '93.1', '93', 'S', 'ARTS, SPORTS ET ACTIVITÉS RÉCRÉATIVES', 'Gestion d''installations sportives'),
  ('93.12Y', '93.12', '93.1', '93', 'S', 'ARTS, SPORTS ET ACTIVITÉS RÉCRÉATIVES', 'Activités des clubs de sports'),
  ('93.13Y', '93.13', '93.1', '93', 'S', 'ARTS, SPORTS ET ACTIVITÉS RÉCRÉATIVES', 'Activités des centres de fitness'),
  ('93.19Y', '93.19', '93.1', '93', 'S', 'ARTS, SPORTS ET ACTIVITÉS RÉCRÉATIVES', 'Autres activités sportives n.c.a.'),
  ('93.21Y', '93.21', '93.2', '93', 'S', 'ARTS, SPORTS ET ACTIVITÉS RÉCRÉATIVES', 'Activités des parcs d''attractions et parcs à thème'),
  ('93.29Y', '93.29', '93.2', '93', 'S', 'ARTS, SPORTS ET ACTIVITÉS RÉCRÉATIVES', 'Activités récréatives et de loisirs n.c.a.'),
  ('94.11Y', '94.11', '94.1', '94', 'T', 'AUTRES ACTIVITÉS DE SERVICES', 'Activités des organisations patronales et des chambres représentatives'),
  ('94.12Y', '94.12', '94.1', '94', 'T', 'AUTRES ACTIVITÉS DE SERVICES', 'Activités des organisations professionnelles'),
  ('94.20Y', '94.20', '94.2', '94', 'T', 'AUTRES ACTIVITÉS DE SERVICES', 'Activités des syndicats de salariés'),
  ('94.91Y', '94.91', '94.9', '94', 'T', 'AUTRES ACTIVITÉS DE SERVICES', 'Activités des organisations religieuses'),
  ('94.92Y', '94.92', '94.9', '94', 'T', 'AUTRES ACTIVITÉS DE SERVICES', 'Activités des organisations politiques'),
  ('94.99Y', '94.99', '94.9', '94', 'T', 'AUTRES ACTIVITÉS DE SERVICES', 'Activités des organisations associatives n.c.a.'),
  ('95.10Y', '95.10', '95.1', '95', 'T', 'AUTRES ACTIVITÉS DE SERVICES', 'Réparation et entretien d''ordinateurs et d''équipements de communication'),
  ('95.21Y', '95.21', '95.2', '95', 'T', 'AUTRES ACTIVITÉS DE SERVICES', 'Réparation et entretien de produits électroniques grand public'),
  ('95.22Y', '95.22', '95.2', '95', 'T', 'AUTRES ACTIVITÉS DE SERVICES', 'Réparation et entretien d''appareils électroménagers et d''équipements pour la maison et le jardin'),
  ('95.23Y', '95.23', '95.2', '95', 'T', 'AUTRES ACTIVITÉS DE SERVICES', 'Réparation et entretien de chaussures et d''articles en cuir'),
  ('95.24Y', '95.24', '95.2', '95', 'T', 'AUTRES ACTIVITÉS DE SERVICES', 'Réparation et entretien de meubles et d''équipements du foyer'),
  ('95.25Y', '95.25', '95.2', '95', 'T', 'AUTRES ACTIVITÉS DE SERVICES', 'Réparation et entretien d''articles d''horlogerie et de bijouterie'),
  ('95.29G', '95.29', '95.2', '95', 'T', 'AUTRES ACTIVITÉS DE SERVICES', 'Réparation et entretien de cycles et autres engins de la mobilité douce'),
  ('95.29H', '95.29', '95.2', '95', 'T', 'AUTRES ACTIVITÉS DE SERVICES', 'Réparation et entretien de tous les autres biens personnels ou domestiques n.c.a.'),
  ('95.31G', '95.31', '95.3', '95', 'T', 'AUTRES ACTIVITÉS DE SERVICES', 'Réparation et entretien de véhicules automobiles légers (moins de 3,5 tonnes)'),
  ('95.31H', '95.31', '95.3', '95', 'T', 'AUTRES ACTIVITÉS DE SERVICES', 'Réparation et entretien d''autres véhicules automobiles'),
  ('95.32Y', '95.32', '95.3', '95', 'T', 'AUTRES ACTIVITÉS DE SERVICES', 'Réparation et entretien de motocycles'),
  ('95.40Y', '95.40', '95.4', '95', 'T', 'AUTRES ACTIVITÉS DE SERVICES', 'Activités de service d''intermédiation pour la réparation et l''entretien d''ordinateurs, de biens personnels et domestiques et d''automobiles et motocycles'),
  ('96.10G', '96.10', '96.1', '96', 'T', 'AUTRES ACTIVITÉS DE SERVICES', 'Blanchisserie-teinturerie de gros'),
  ('96.10H', '96.10', '96.1', '96', 'T', 'AUTRES ACTIVITÉS DE SERVICES', 'Blanchisserie-teinturerie de détail'),
  ('96.21G', '96.21', '96.2', '96', 'T', 'AUTRES ACTIVITÉS DE SERVICES', 'Coiffure et activités de barbier en salon'),
  ('96.21H', '96.21', '96.2', '96', 'T', 'AUTRES ACTIVITÉS DE SERVICES', 'Coiffure et activités de barbier hors salon'),
  ('96.22Y', '96.22', '96.2', '96', 'T', 'AUTRES ACTIVITÉS DE SERVICES', 'Soins de beauté et autres activités de traitement esthétique'),
  ('96.23Y', '96.23', '96.2', '96', 'T', 'AUTRES ACTIVITÉS DE SERVICES', 'Activités de spa, de sauna et de bain de vapeur'),
  ('96.30Y', '96.30', '96.3', '96', 'T', 'AUTRES ACTIVITÉS DE SERVICES', 'Services funéraires et activités connexes'),
  ('96.40Y', '96.40', '96.4', '96', 'T', 'AUTRES ACTIVITÉS DE SERVICES', 'Activités de service d''intermédiation pour des services aux personnes'),
  ('96.91Y', '96.91', '96.9', '96', 'T', 'AUTRES ACTIVITÉS DE SERVICES', 'Activités d''offre de services domestiques aux personnes'),
  ('96.99G', '96.99', '96.9', '96', 'T', 'AUTRES ACTIVITÉS DE SERVICES', 'Services pour animaux de compagnie'),
  ('96.99H', '96.99', '96.9', '96', 'T', 'AUTRES ACTIVITÉS DE SERVICES', 'Toutes les autres activités de service aux personnes n.c.a.'),
  ('97.00Y', '97.00', '97.0', '97', 'U', 'ACTIVITÉS DES MÉNAGES EN TANT QU''EMPLOYEURS ; ACTIVITÉS INDIFFÉRENCIÉES DES MÉNAGES EN TANT QUE PRODUCTEURS DE BIENS ET SERVICES POUR USAGE PROPRE', 'Activités des ménages en tant qu''employeurs de personnel domestique'),
  ('98.10Y', '98.10', '98.1', '98', 'U', 'ACTIVITÉS DES MÉNAGES EN TANT QU''EMPLOYEURS ; ACTIVITÉS INDIFFÉRENCIÉES DES MÉNAGES EN TANT QUE PRODUCTEURS DE BIENS ET SERVICES POUR USAGE PROPRE', 'Activités indifférenciées des ménages en tant que producteurs de biens pour usage propre'),
  ('98.20Y', '98.20', '98.2', '98', 'U', 'ACTIVITÉS DES MÉNAGES EN TANT QU''EMPLOYEURS ; ACTIVITÉS INDIFFÉRENCIÉES DES MÉNAGES EN TANT QUE PRODUCTEURS DE BIENS ET SERVICES POUR USAGE PROPRE', 'Activités indifférenciées des ménages en tant que producteurs de services pour usage propre'),
  ('99.00Y', '99.00', '99.0', '99', 'V', 'ACTIVITÉS DES ORGANISATIONS ET ORGANISMES EXTRATERRITORIAUX', 'Activités des organisations et organismes extraterritoriaux');
