# API
DEV = true
APP_BIND = ":5000"

# Paramètrage de l'import
APP_DATA = "/foo/bar/data-raw"
NAF_L1 =   "/foo/bar/data-raw/naf/naf1.csv"
NAF_L2 =   "/foo/bar/data-raw/naf/naf2.csv"
NAF_L3 =   "/foo/bar/data-raw/naf/naf3.csv"
NAF_L4 =   "/foo/bar/data-raw/naf/naf4.csv"
NAF_l5 =   "/foo/bar/data-raw/naf/naf5.csv"
NAF_5to1 = "/foo/bar/data-raw/naf/5to1.csv"

# Connexion à la base de données
DB_DIAL = "mongodb://localhost:27017"
DB = "signauxfaibles"
FIRST_BATCH = "1802"

# Parallélisme du MapReduce
MRthreads = 2
chunkByteSize = 1000000000

# connexion à datapi
datapiURL = "http://localhost:3000/"
datapiUser = "Some_User"
datapiPassword = "Some_Strong_Password"
datapiChunk = 2000 
