name: CI

on:
  push:
    branches:

jobs:
  build:
    name: Generate and lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - run: make build
      - name: Check that generated files are up to date (variables.json)
        run: |
          go generate -x ./...
          git diff
          exit $(git diff | wc -l)

  go-tests:
    name: Go tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - run: make build
      - run: cp config-sample.toml config.toml

      - run: go test -v -coverprofile=go-coverage.out -covermode=atomic -coverpkg=./... ./...
      - name: Show coverage
        run: go tool cover -func=go-coverage.out


  e2e-tests:
    name: End-to-end tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - run: make build

      - name: Crée le fichier de configuration minimal
        run: |
          touch config.toml
          echo "[log]" >> config.toml
          echo "level = \"error\"" >> config.toml

      - run: ./tests/test-check.sh

      - run: go test -tags=e2e
