name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  go-tests:
    name: Go functions
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go
      - name: Check out code
        uses: actions/checkout@v2
      - name: Go test (with coverage)
        run: |
          go test -coverprofile=go-coverage.out -covermode count ./...
          go run github.com/t-yuki/gocover-cobertura < go-coverage.out > go-coverage.xml
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report-1
          path: go-coverage.xml

  mr-tests:
    name: Map-Reduce functions
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Check out code
        uses: actions/checkout@v2
      - name: Use cache for Node/npm dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
      - name: Install Node/npm dependencies
        working-directory: js
        env:
          CI: true
        run: npm install --prefer-offline --no-audit
      - name: Check that jsFunctions.go is up to date
        working-directory: lib/engine
        run: |
          go generate -x
          git diff jsFunctions.go
          exit $(git diff jsFunctions.go | wc -l)
      - name: JS Linter
        working-directory: js
        run: |
          npm run lint
      - name: Reveal golden master files for tests
        env:
          GPG_PRIVATE_KEY_FOR_GIT_SECRET: ${{ secrets.GPG_PRIVATE_KEY_FOR_GIT_SECRET }}
        run: |
          sudo apt-get install git-secret # to decrypt golden master files, for tests
          echo "${GPG_PRIVATE_KEY_FOR_GIT_SECRET}" > ./private_key.gpg
          gpg --import --no-tty --batch --yes ./private_key.gpg
          git secret reveal
      - name: Tests driven by Node/AVA
        working-directory: js
        run: |
          npm run test:coverage
          npx nyc report --reporter=lcov --include="**/*.ts" --exclude="**/*.js" # stores the coverage report in ./coverage/lcov.info
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report-2
          path: js/coverage/lcov.info

  coverage:
    name: Send coverage data to Codacy
    needs:
      - mr-tests
      - go-tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Download code coverage reports
        uses: actions/download-artifact@v2
      - name: Upload coverage to codacy
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_REPOSITORY_TOKEN_FOR_COVERAGE }}
          coverage-reports: go-coverage.xml,js/coverage/lcov.info
