name: End-to-end CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        working-directory: dbmongo
        run: go build -v .

      - name: Install test dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y httpie
          sudo apt-get install git-secret # to decrypt golden master files, for tests

      - name: Reveal golden master files for tests
        env:
          GPG_PRIVATE_KEY_FOR_GIT_SECRET: ${{ secrets.GPG_PRIVATE_KEY_FOR_GIT_SECRET }}
        run: |
          echo "${GPG_PRIVATE_KEY_FOR_GIT_SECRET}" > ./private_key.gpg
          gpg --import --no-tty --batch --yes ./private_key.gpg
          git secret reveal

      - run: /test-api.sh

      - run: ./test-api-2.sh # relies on golden master files

      - run: ./test-api-reduce.sh
