name: Go CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Check that jsFunctions.go is up to date
      working-directory: dbmongo/lib/engine
      run: |
        go generate -x
        git diff jsFunctions.go
        exit $(git diff jsFunctions.go | wc -l)

    - name: Build
      working-directory: dbmongo
      run: go build -v .

    - name: Install test dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libjavascriptcoregtk-4.0-bin # for tests of JavaScript functions
        sudo apt-get install -y dos2unix # for Diane tests

    - name: Tests
      working-directory: dbmongo
      run: TZ=CET go test ./... # note: js_test.go relies on Date comparisons in the CET timezone

    - name: New JS Tests
      working-directory: dbmongo/js
      run: |
        sudo apt-get install -y nodejs
        npm install
        TZ=CET npm run test:coverage # TODO: let's check if we can get rid of the TZ env var
        npx nyc report --reporter=lcov # stores the coverage report in ./coverage/lcov.info

    - name: Upload coverage to codacy
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_REPOSITORY_TOKEN_FOR_COVERAGE }}
        coverage-reports: dbmongo/js/coverage/lcov.info
