name: Go CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Generate jsFunctions.go
      working-directory: dbmongo/lib/engine
      run: |
        go generate -x

    - name: Build
      working-directory: dbmongo
      run: go build -v .

    - name: Install test dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libjavascriptcoregtk-4.0-bin # for tests of JavaScript functions
        sudo apt-get install -y dos2unix # for Diane tests

    - name: Test dbmongo
      working-directory: dbmongo
      run: TZ=CET go test -v # includes js_test.go, which relies on Date comparisons in the CET timezone

    - name: Test file parsers
      working-directory: dbmongo/lib
      run: |
        go test -v ./apconso
        go test -v ./apdemande
        go test -v ./bdf
        go test -v ./diane
        go test -v ./marshal
        go test -v ./reporder
        go test -v ./sirene
        go test -v ./sirene_ul
        go test -v ./urssaf

    - name: Test engine
      working-directory: dbmongo/lib/engine
      run: go test -v

    - name: Test everything
      working-directory: dbmongo
      run: go test -v ./...
