name: Go CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      run: |
        export GO111MODULE="on" # see https://github.com/kubernetes/client-go/blob/master/INSTALL.md#installing-client-go
        go get github.com/signaux-faibles/opensignauxfaibles@${GITHUB_REF}

    - name: Build
      run: |
        cd $(go env GOPATH)/src/github.com/signaux-faibles/opensignauxfaibles/dbmongo
        go build -v .
    
    - name: Test
      run: |
        cd $(go env GOPATH)/src/github.com/signaux-faibles/opensignauxfaibles/dbmongo
        go test -v
